### ISSUE TITLE
Let the SpotifySavedAlbum-import list monitor all spotify-saved albums

### ISSUE THREAD

**Issue by kromsam** [Lidarr/Lidarr#2855] opened 2022-06-27 13:08 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I use the SpotifySavedAlbum import list to mirror my Spotify music library with the library I manage with Lidarr.

Recently I discovered that the import list does not monitor albums I have saved on Spotify by artists already in my Lidarr library. I thought this was odd, because this seems to be an arbitrary distinction.

Why does the list monitor some albums you save on Spotify (albums of artists that are not yet in Lidarr), and why doesn't the list monitor other albums (the albums of artists you already have added in Lidarr)?

I addressed this issue as a bug last week. But apparently it was not a bug (to my surprise):
https://github.com/Lidarr/Lidarr/issues/2850

Because it is not a bug I address this issue again, but as a feature request (which, I gotta say, feels a bit tedious).

### Describe the solution you'd like

What I expect is very simple:

- I save **any** album on Spotify
- This album (and only this album!) is monitored by Lidarr

I am very happy that this works for almost all albums I add on Spotify. This import list is really a great feature. It is just frustrating that I cannot rely on it when it comes to some artists.

### Describe alternatives you've considered

Now I have to monitor these albums manually which kinda defeats the purpose of using an import list.

### Anything else?

Have a look at the bug request I posted for more details on the configuration I use and some relevant logs:

https://github.com/Lidarr/Lidarr/issues/2850

[AB#3320](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3320)

**Comment by Kuglikrug** [comment] 2022-07-19 12:53
I second this!
This is my experience right now:
I sync a Spotify playlist to lidarr and lets say in that playlist there are two songs from Snoop Dogg:

_1. Snoop Dogg - Doggumentary - Take U Home_
_2. Snoop Dogg - Tha Blue Carpet Treatment - Vato_

After the first sync, the Artist Snoop Dogg appears in Lidarr with the two albums marked as "monitored" and "missing".
If i hit "refresh & scan" on the newly added Artist Snoop Dogg, all of his Albums get loaded into Lidarr (with still only the two albums above being "monitored" or marked as "wanted").

lets say i add a third song to my Spotify playlist
_3. Snoop Dogg - R&G (Rhythm & Gangsta): The Masterpiece - Let’s Get Blown_

This album is indeed listed in Lidarr (since i hit the "refresh & scan" button earlier) but neither available nor monitored.

After the next spotify->lidarr list-sync i would expect the album _R&G (Rhythm & Gangsta): The Masterpiece_ to switch from "non monitored" to "monitored", triggering the download.

Instead there is no change at all and the new album does not get monitored.

**Comment by ta264** [comment] 2022-07-19 13:28
This is a duplicate of #2411

**Closed as completed by ta264** 2022-07-19 13:28 UTC
Labels: Type: Duplicate, Type: Feature Request

**Comment by Kuglikrug** [comment] 2022-07-19 21:35
@kromsam lets emphasize the importance over at #2411
