### ISSUE TITLE
Library Album\Song View

### ISSUE THREAD

**Issue by ren-del** [Lidarr/Lidarr#4695] opened 2024-03-22 16:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently when browsing the library in Lidarr it is set to artist view only, would like the ability to view all albums at once instead of all artists. This makes monitoring, searching for missing albums and viewability a lot easier. Currently you have to open the artist page to view what albums they have and then you have to go into album to see what songs are missing

### Describe the solution you'd like

Ability to switch from Artist View to Album or Song View when looking at library. This can be a separate section or a toggle in the existing UI. This would vastly expand what Lidarr could be used for, and give a similar view to what already exists in various music management / player software, ie. MusicBee/iTunes.

### Describe alternatives you've considered

Currently I have to constantly expand or import library into another application to easily view everything at once.

### Anything else?

Album View Example
![image](https://github.com/Lidarr/Lidarr/assets/90739730/26680cc3-a2b4-4a46-99f2-692dd0fb35be)

Song View Example
![image](https://github.com/Lidarr/Lidarr/assets/90739730/93ae766d-b74b-4bce-80df-c83e9685d1a4)

**Comment by bakerboy448** [comment] 2024-03-22 17:50
Duplicate of https://github.com/Lidarr/Lidarr/issues/4336

**Closed by bakerboy448** 2024-03-22 17:50 UTC
Labels: Type: Feature Request, Status: Needs Triage
