### ISSUE TITLE
not scanning library

### ISSUE THREAD

**Issue by vrtlspd** [Lidarr/Lidarr#2769] opened 2022-04-19 17:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's aborting the library scan when encountering accents or special charactes in the file name.

### Expected Behavior

go throught the entire library

### Steps To Reproduce

1. just hit "update all" from the library tab

### Environment

```markdown
- OS: Linux OPENMEDIAVAULT 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64
- Lidarr: 0.8.1.2135-ls78 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 98
```

### What branch are you running?

Master

### Trace Logs?

[Info] ImportDecisionMaker: Reading file 217/11120 
[Info] ImportDecisionMaker: Reading file 218/11120 
[Error] CommandExecutor: Error occurred while executing task RescanFolders 
[v0.8.1.2135] System.IO.FileNotFoundException: Could not find file '/music/Leaves' Eyes - Lovelorn/03 - Ocean�s Way.mp3'.
File name: '/music/Leaves' Eyes - Lovelorn/03 - Ocean�s Way.mp3'
   at System.IO.FileInfo.get_Length()
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetLocalTracks(List`1 musicFiles, DownloadClientItem downloadClientItem, ParsedTrackInfo folderInfo, FilterFilesType filter) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 108
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 145
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 157
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 285
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

[AB#3015](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3015)

**Comment by bakerboy448** [comment] 2022-04-19 17:21
Duplicate of https://github.com/Lidarr/Lidarr/issues/1727

**Closed** 2022-04-19 17:22 UTC
Labels: Type: Support
