### ISSUE TITLE
Lidarr can't see releases with "unkown" status in MusicBrainz

### ISSUE THREAD

**Issue by mstargard** [lidarr/Lidarr#1069] opened 2020-01-28 00:39 UTC
A release of an album has these statuses in MusicBrainz:
- Official
- Promotion
- Bootleg
- Official
- NULL

If the release does not have a status marked in MB, then it cannot be seen by Lidarr. For example,

https://musicbrainz.org/release-group/251809c8-7edc-4607-9557-022e2af709fc

Notice how this release-group has one release that has no status. This is just one example.

**To Reproduce**
1. Get the release somehow other than Lidarr. 
2. Try to import the release with all statuses checked in the release profile with the Primary and Secondary release types matching MusicBrainz for the release.
3. Try to import the release. It will not match. In this case, it only matches the tracks for the release it sees in MB, which is a subset of all the tracks.

**Expected behavior**
Lidarr should match the release. Perhaps it should have another checkbox for "unknown" status in the profile?

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Ubuntu Server 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 6.8.0.96

**Comment by ta264** [comment] 2020-01-28 10:15
Dupe of #781. Edit it on musicbrainz to have the correct release status.

**Closed by ta264** 2020-01-28 10:15 UTC
