### ISSUE TITLE
Lidarr requires write permissions on import directories

### ISSUE THREAD

**Issue by dippynark** [lidarr/Lidarr#968] opened 2019-09-09 12:31 UTC
**Describe the bug**
When trying to import artists from a read only directory I am seeing
```
[Warn] LidarrErrorPipeline: Invalid request Validation failed:
 -- Folder is not writable by user abc
```
It should be possible to supply existing files readonly to protect them as is possible with both Sonarr and Radarr.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Artist'
2. Click on 'Import Existing Artist(s)'
3. Click on 'Start Import'
4. Select read only directory
5. See error in logs

**Expected behaviour**
Lidarr to scan read only directories for artists

**System info (please complete the following information):**
 - Lidarr Version: `0.6.2.883`
 - Operating System: Linux
 - .mono (macOS/Linux) Version: `5.20.1.34`

**Additional Context**
I have my own download pipeline for finished torrents and do not want Lidarr manipulating any music files, I just want to use it for adding torrents to my client - this setup works well with Sonarr and Radarr.

**Comment by ta264** [comment] 2019-09-09 13:02
Duplicate of #815.  Pretty sure this isn't allowed in Sonarr/Radarr either - what's the point of Lidarr if it can't add files to the library?

**Closed by ta264** 2019-09-09 13:02 UTC

**Comment by dippynark** [comment] 2019-09-10 08:35
Sorry for the dup, the purpose would be to search for missing albums and add them to my torrent client - I use radarr and sonarr for solely this purpose (with my own download pipeline) and it works very well

**Comment by dippynark** [comment] 2019-09-10 08:37
I don't mount the files in radarr and sonarr read only, but they come from a read only NFS export and they still work, Lidarr does more checks it seems when scanning and so fails to work at all with that setup

**Comment by ta264** [comment] 2019-09-10 08:44
Sonarr V2 or V3?

**Comment by ta264** [comment] 2019-09-10 08:49
Yeah, pretty sure this won't work in sonarr v3

**Comment by dippynark** [comment] 2019-09-10 10:42
I'm not too sure, this is the version info I'm seeing:
```
Version
10.0.0.34649
Mono Version
5.20.1.34
```

**Comment by ta264** [comment] 2019-09-10 10:46
That means you've built yourself from source. If you're using the newer phantom or phantom-develop branch then I suspect it won't work.
