### ISSUE TITLE
Unable to refresh artist Clint Mansell

### ISSUE THREAD

**Issue by Magnus010** [lidarr/Lidarr#833] opened 2019-06-09 23:01 UTC
**Describe the bug**
Attempting to refresh the artist Clint Mansell results in a Failed notification.

**To Reproduce**
Metadata profile is set to everything but Spokenword, Interview, and DJ-Mix
1. Go to artist Clint Mansell
2. Click on "Refresh and Scan"
3. See error

**Expected behavior**
No artist information is updated. Profile in Musicbrainz DB shows many albums: https://musicbrainz.org/artist/fc015f11-be38-4b7d-b3e8-5d809242ecec. Lidarr shows three (Filth, Last Night, Definitely- Maybe)

**Logs**
Message
```Error occurred while executing task RefreshArtist: Object reference not set to an instance of an object```
Exception
```System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Music.AddAlbumService.AddAlbum (System.Tuple`3[T1,T2,T3] skyHookData) [0x0007d] in C:\projects\lidarr\src\NzbDrone.Core\Music\AddAlbumService.cs:100 
  at NzbDrone.Core.Music.AddAlbumService.AddAlbums (System.Collections.Generic.List`1[T] newAlbums) [0x00045] in C:\projects\lidarr\src\NzbDrone.Core\Music\AddAlbumService.cs:130 
  at NzbDrone.Core.Music.RefreshArtistService.RefreshArtistInfo (NzbDrone.Core.Music.Artist artist, System.Boolean forceAlbumRefresh) [0x00319] in C:\projects\lidarr\src\NzbDrone.Core\Music\RefreshArtistService.cs:154 
  at NzbDrone.Core.Music.RefreshArtistService.Execute (NzbDrone.Core.Music.Commands.RefreshArtistCommand message) [0x00089] in C:\projects\lidarr\src\NzbDrone.Core\Music\RefreshArtistService.cs:234 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000f6] in C:\projects\lidarr\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:95 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\projects\lidarr\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41
```

**System info (please complete the following information):**
 - Lidarr Version: 0.6.2.883
 - Operating System: Docker on Ubunto host
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.19

Thank you!

**Comment by Qstick** [comment] 2019-06-09 23:20
@ta264 looks like this is because metadata doesn't return Clint Mansell as the artist for this album, even though he is first on the release group record (https://beta.musicbrainz.org/release-group/0e50740d-1531-4522-bd3d-dab430c2592b). 

Metadata: https://api.lidarr.audio/api/v0.4/album/0e50740d-1531-4522-bd3d-dab430c2592b

Instead it returns the second artist on the album as the main (https://beta.musicbrainz.org/artist/0529a9e0-befb-4d9f-b6f9-1ccd7c83053e), this seems to be a recent regression in metadata, as this was not always the behavior 

This causes Lidarr to fail given the album has incorrect artist and there is not metadata record for that artist.

**Comment by ta264** [comment] 2019-06-10 03:41
Should be fixed now, sorry for the disruption

**Closed by ta264** 2019-06-10 03:41 UTC
Labels: Area: Metadata API

**Comment by Magnus010** [comment] 2019-06-10 03:45
Awesome, thanks for looking into this!
