### ISSUE TITLE
Allow DVD and Blu-ray sources 

### ISSUE THREAD

**Issue by jprjr** [Lidarr/Lidarr#4123] opened 2023-09-17 12:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently Lidarr discards DVD and Blu-ray media as non-audio media, defined here: https://github.com/Lidarr/Lidarr/blob/d8ed41f5e88ee4e404b7d386d40be1eb1a69a8d8/src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs#L28

I'm unable to select releases that are only made of these media.

In the case of Blu-ray, MusicBrainz doesn't distinguish between audio-only Blu-ray and others, but audio-only discs do exist. https://en.wikipedia.org/wiki/High_Fidelity_Pure_Audio

For DVD video, it's not uncommon to rip audio from a concert into tracks and to tag them using MusicBrainz data.

### Describe the solution you'd like

I think removing DVD and Blu-ray from the non-audio list would be the quickest solution. Users may see extra releases listed but I don't think that would bother people too much.

Another idea is to make it a configurable setting. Maybe as a global option, or a release group option (so when choosing a release, a user could check a "include non-audio media" box)

### Describe alternatives you've considered

One alternative is picking another release on different media, but this only works if there's another release with the same tracks.

My Blu-ray version of "Never Mind The Bollocks Here's The Sex Pistols" doesn't have a release on other media with the same tracks. https://musicbrainz.org/release/a4898dcc-1e74-4c2b-b5ce-ba8ace4ab45b

### Anything else?

In a previous issue on this (now locked, hence why I'm opening a new issue) it was mentioned that Blu-ray is omitted because it's video, not audio. This just isn't the case, as they can either be ripped, or include a download code to get the release in FLAC. https://github.com/Lidarr/Lidarr/issues/2084#issuecomment-798798987

**Comment by bakerboy448** [comment] 2023-09-17 13:08
Duplicate of several issues

**Closed by bakerboy448** 2023-09-17 13:08 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by jprjr** [comment] 2023-09-17 13:43
I'd like to request this be re-opened.

This is marked as a duplicate of other issues, which are all locked so I can't raise anything there.

The closure reason for the duplicates is the assertion that blu-ray and DVD aren't audio sources but I think my issue (and the closed ones) assert that is not a correct assumption.
