### ISSUE TITLE
Allow searching all artist's albums for a song

### ISSUE THREAD

**Issue by phirestalker** [Lidarr/Lidarr#4067] opened 2023-08-25 14:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some artists have a LOT of albums, and I currently have to use third party sources to _try_ and find what albums they are on.

### Describe the solution you'd like

I'm not sure how it would be implemented. I guess in the artist's page you would have another search box to filter the listed albums based on the search. I would input a song I am looking for and it would only show the albums that have that song. That is the cleanest way I can imagine, but you guys know best.

### Describe alternatives you've considered

I don't know any.

### Anything else?

I am not sure what search terms to use, but I tried a few and didn't see anything. Sorry if this has already been asked.

**Comment by bakerboy448** [comment] 2023-08-26 12:40
Duplicate of https://github.com/Lidarr/Lidarr/issues/569

**Closed by bakerboy448** 2023-08-26 12:40 UTC
Labels: Type: Feature Request, Status: Needs Triage
