### ISSUE TITLE
Lidarr internal update under Windows 

### ISSUE THREAD

**Issue by phit42** [Lidarr/Lidarr#5231] opened 2024-11-10 16:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Lidarr's internal update on a Windows machine does not correctly register its current version (and potentially other information), resulting in misrepresented versioning under Windows and issues with update tools like winget.
![image](https://github.com/user-attachments/assets/26ebd354-3be0-40fb-8fc7-1510df673a1c)
![image](https://github.com/user-attachments/assets/7be59b5c-f3ef-4149-9688-90b2f4fffbb0)

### Expected Behavior

Installed version should be correctly registered within Windows itself.

### Steps To Reproduce

Install previous version with setup program under Windows 10 or 11. Update to latest version via Lidarr's internal functionalities.

### Environment

```markdown
- OS: Windows 10, 22H2
- Lidarr: Lidarr 2.7.1.4417
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Edge
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

2024-11-10 16:55:50.3|Info|InstallUpdateService|Deleting old update files
2024-11-10 16:55:50.8|Info|InstallUpdateService|Downloading update 2.7.1.4417
2024-11-10 16:56:08.6|Info|InstallUpdateService|Verifying update package
2024-11-10 16:56:08.8|Info|InstallUpdateService|Update package verified successfully
2024-11-10 16:56:08.8|Info|InstallUpdateService|Extracting Update package
2024-11-10 16:56:16.2|Info|InstallUpdateService|Update package extracted successfully
2024-11-10 16:56:16.2|Info|BackupService|Starting Backup
2024-11-10 16:57:01.6|Info|InstallUpdateService|Preparing client
2024-11-10 16:57:07.3|Info|InstallUpdateService|Starting update client C:\Users\(removed)\AppData\Local\Temp\lidarr_update\Lidarr.Update.exe
2024-11-10 16:57:07.3|Info|InstallUpdateService|Lidarr will restart shortly.
2024-11-10 16:57:07.3|Info|InstallUpdateService|Updater Arguments: 29660 C:\Users\(removed)\AppData\Local\Temp\lidarr_update C:\ProgramData\Lidarr\bin\Lidarr.exe 
2024-11-10 16:57:07.4|Info|DiskScanService|Scanning C:\Users\(removed)\Music\NewMusic
2024-11-10 16:57:47.9|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.exe - Version 2.7.1.4417
2024-11-10 16:57:48.5|Info|MigrationController|*** Migrating data source=C:\ProgramData\Lidarr\lidarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
2024-11-10 16:57:48.6|Info|FluentMigrator.Runner.MigrationRunner|DatabaseEngineVersionCheck migrating
2024-11-10 16:57:48.6|Info|FluentMigrator.Runner.MigrationRunner|PerformDBOperation 
2024-11-10 16:57:48.6|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|Performing DB Operation
2024-11-10 16:57:48.6|Info|DatabaseEngineVersionCheck|SQLite 3.36.0
2024-11-10 16:57:48.6|Info|FluentMigrator.Runner.MigrationRunner|=> 0,0416113s
2024-11-10 16:57:48.6|Info|FluentMigrator.Runner.MigrationRunner|DatabaseEngineVersionCheck migrated
2024-11-10 16:57:48.6|Info|FluentMigrator.Runner.MigrationRunner|=> 0,0429882s
2024-11-10 16:57:48.7|Info|MigrationController|*** Migrating data source=C:\ProgramData\Lidarr\logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
2024-11-10 16:57:48.7|Info|FluentMigrator.Runner.MigrationRunner|DatabaseEngineVersionCheck migrating
2024-11-10 16:57:48.7|Info|FluentMigrator.Runner.MigrationRunner|PerformDBOperation 
2024-11-10 16:57:48.7|Info|NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor|Performing DB Operation
2024-11-10 16:57:48.7|Info|DatabaseEngineVersionCheck|SQLite 3.36.0
2024-11-10 16:57:48.7|Info|FluentMigrator.Runner.MigrationRunner|=> 0,0018823s
2024-11-10 16:57:48.7|Info|FluentMigrator.Runner.MigrationRunner|DatabaseEngineVersionCheck migrated
2024-11-10 16:57:48.7|Info|FluentMigrator.Runner.MigrationRunner|=> 0,0022307s
2024-11-10 16:57:49.0|Info|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:8686

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2024-11-10 16:53
- not a bug
- No plans beyond https://github.com/Lidarr/Lidarr/issues/3772
- Closing in favor of sonarr pull issue https://github.com/Lidarr/Lidarr/issues/3772
- ref https://github.com/Prowlarr/Prowlarr/issues/1715

**Closed by bakerboy448** 2024-11-10 16:53 UTC
Labels: Type: Bug, Status: Needs Triage
