### ISSUE TITLE
Dakuten and handakuten removed from Artist name

### ISSUE THREAD

**Issue by adamjsturge** [Lidarr/Lidarr#3248] opened 2022-12-27 20:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Similar to https://github.com/Lidarr/Lidarr/issues/326
ポルカドットスティングレイ becomes ホルカトットスティンクレイ
It removes the Dakuten and handakuten when it sends to both Jackett and Prowlarr. Just tested it for Artist not sure if it's for song/album as well

### Expected Behavior

The Artist name:
ポルカドットスティングレイ
stays the same

### Steps To Reproduce

1) Add ポルカドットスティングレイ as artist
2) Notice how the first character loses the circle on it

### Environment

```markdown
Version: 1.0.2.2592
Package Version: 1.0.2.2592-1 by lidarr
.NET: Yes (6.0.4)
Docker: Yes
DB Migration: 56
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#4561](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4561)

**Comment by adamjsturge** [comment] 2022-12-28 18:07
Also happens with Albums names as well

**Comment by xiaoxi654** [comment] 2023-04-03 15:37
2023, it didn’t get fixed :(

**Comment by bakerboy448** [comment] 2023-05-15 05:24
Duplicate of #326

**Closed by bakerboy448** 2023-05-15 05:24 UTC
Labels: Type: Bug, Status: Needs Triage
