### ISSUE TITLE
Albums starting with an Ellipsis (...) do not stay as imported.

### ISSUE THREAD

**Issue by tro-co** [lidarr/Lidarr#604] opened 2019-01-26 16:35 UTC
## Bug Report

When an album starts with ... (Ellipsis), the album does not stay imported.  Even after manually importing, the album will no longer be imported after the next scheduled scan.

For instance: Metallica - ...and Justice for All

### System Information/Logs

**Lidarr Version:**0.5.0.583  DB Migration: 22

**Operating System:** Windows 10 Pro

**Comment by ta264** [comment] 2019-01-30 14:49
Please can you post some track logs of an import that removes the album?  I can't reproduce this.

**Comment by tro-co** [comment] 2019-02-04 16:06
I tested with Britney Spear's ...Baby one more time album.  However this occurs on all my albums starting with an ellipsis.  Please let me know if you need more, or what specific information you need.  I also turned on trace logging during the automated scan, but I didn't see anything in those logs of relevance, but maybe there's something in there you would know better.

19-2-4 03:35:01.1|Info|RefreshArtistService|Skipping refresh of artist: Britney Spears
19-2-4 03:35:01.1|Info|DiskScanService|Scanning Britney Spears
19-2-4 03:35:01.1|Debug|DiskScanService|Scanning 'F:\Music\Albums\Albums\Britney Spears' for music files
19-2-4 03:35:01.1|Debug|DiskScanService|122 audio files were found in F:\Music\Albums\Albums\Britney Spears
19-2-4 03:35:01.1|Debug|DiskScanService|[45a663b5-b1cb-4a91-bff6-2bef7bbfdd76][Britney Spears] Cleaning up media files in DB
19-2-4 03:35:01.1|Debug|TrackService|Getting Tracks for ArtistId 152
19-2-4 03:35:01.2|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\01 - Britney Spears - ...Baby One More Time.flac] no longer exists on disk, removing from db
19-2-4 03:35:01.2|Debug|TrackService|Detaching track 36077 from file.
19-2-4 03:35:01.2|Debug|LyricFileService|Deleting Extra from database for track file: [84994] ...Baby One More Time (1999)\01 - Britney Spears - ...Baby One More Time.flac
19-2-4 03:35:01.2|Debug|OtherExtraFileService|Deleting Extra from database for track file: [84994] ...Baby One More Time (1999)\01 - Britney Spears - ...Baby One More Time.flac
19-2-4 03:35:01.2|Debug|MetadataFileService|Deleting Extra from database for track file: [84994] ...Baby One More Time (1999)\01 - Britney Spears - ...Baby One More Time.flac
19-2-4 03:35:01.5|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\02 - Britney Spears - (You Drive Me) Crazy.flac] no longer exists on disk, removing from db
19-2-4 03:35:01.5|Debug|TrackService|Detaching track 36080 from file.
19-2-4 03:35:01.5|Debug|LyricFileService|Deleting Extra from database for track file: [84995] ...Baby One More Time (1999)\02 - Britney Spears - (You Drive Me) Crazy.flac
19-2-4 03:35:01.5|Debug|OtherExtraFileService|Deleting Extra from database for track file: [84995] ...Baby One More Time (1999)\02 - Britney Spears - (You Drive Me) Crazy.flac
19-2-4 03:35:01.6|Debug|MetadataFileService|Deleting Extra from database for track file: [84995] ...Baby One More Time (1999)\02 - Britney Spears - (You Drive Me) Crazy.flac
19-2-4 03:35:01.8|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\03 - Britney Spears - Sometimes.flac] no longer exists on disk, removing from db
19-2-4 03:35:01.8|Debug|TrackService|Detaching track 36081 from file.
19-2-4 03:35:01.9|Debug|LyricFileService|Deleting Extra from database for track file: [84996] ...Baby One More Time (1999)\03 - Britney Spears - Sometimes.flac
19-2-4 03:35:01.9|Debug|OtherExtraFileService|Deleting Extra from database for track file: [84996] ...Baby One More Time (1999)\03 - Britney Spears - Sometimes.flac
19-2-4 03:35:01.9|Debug|MetadataFileService|Deleting Extra from database for track file: [84996] ...Baby One More Time (1999)\03 - Britney Spears - Sometimes.flac
19-2-4 03:35:02.1|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\04 - Britney Spears - Soda Pop.flac] no longer exists on disk, removing from db
19-2-4 03:35:02.2|Debug|TrackService|Detaching track 36082 from file.
19-2-4 03:35:02.2|Debug|LyricFileService|Deleting Extra from database for track file: [84997] ...Baby One More Time (1999)\04 - Britney Spears - Soda Pop.flac
19-2-4 03:35:02.2|Debug|OtherExtraFileService|Deleting Extra from database for track file: [84997] ...Baby One More Time (1999)\04 - Britney Spears - Soda Pop.flac
19-2-4 03:35:02.2|Debug|MetadataFileService|Deleting Extra from database for track file: [84997] ...Baby One More Time (1999)\04 - Britney Spears - Soda Pop.flac
19-2-4 03:35:02.5|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\05 - Britney Spears - Born To Make You Happy.flac] no longer exists on disk, removing from db
19-2-4 03:35:02.5|Debug|TrackService|Detaching track 36083 from file.
19-2-4 03:35:02.5|Debug|LyricFileService|Deleting Extra from database for track file: [84998] ...Baby One More Time (1999)\05 - Britney Spears - Born To Make You Happy.flac
19-2-4 03:35:02.5|Debug|OtherExtraFileService|Deleting Extra from database for track file: [84998] ...Baby One More Time (1999)\05 - Britney Spears - Born To Make You Happy.flac
19-2-4 03:35:02.5|Debug|MetadataFileService|Deleting Extra from database for track file: [84998] ...Baby One More Time (1999)\05 - Britney Spears - Born To Make You Happy.flac
19-2-4 03:35:02.8|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\06 - Britney Spears - From The Bottom Of My Broken Heart.flac] no longer exists on disk, removing from db
19-2-4 03:35:02.8|Debug|TrackService|Detaching track 36084 from file.
19-2-4 03:35:02.8|Debug|LyricFileService|Deleting Extra from database for track file: [84999] ...Baby One More Time (1999)\06 - Britney Spears - From The Bottom Of My Broken Heart.flac
19-2-4 03:35:02.8|Debug|OtherExtraFileService|Deleting Extra from database for track file: [84999] ...Baby One More Time (1999)\06 - Britney Spears - From The Bottom Of My Broken Heart.flac
19-2-4 03:35:02.9|Debug|MetadataFileService|Deleting Extra from database for track file: [84999] ...Baby One More Time (1999)\06 - Britney Spears - From The Bottom Of My Broken Heart.flac
19-2-4 03:35:03.1|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\07 - Britney Spears - I Will Be There.flac] no longer exists on disk, removing from db
19-2-4 03:35:03.1|Debug|TrackService|Detaching track 36085 from file.
19-2-4 03:35:03.1|Debug|LyricFileService|Deleting Extra from database for track file: [85000] ...Baby One More Time (1999)\07 - Britney Spears - I Will Be There.flac
19-2-4 03:35:03.1|Debug|OtherExtraFileService|Deleting Extra from database for track file: [85000] ...Baby One More Time (1999)\07 - Britney Spears - I Will Be There.flac
19-2-4 03:35:03.2|Debug|MetadataFileService|Deleting Extra from database for track file: [85000] ...Baby One More Time (1999)\07 - Britney Spears - I Will Be There.flac
19-2-4 03:35:03.4|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\08 - Britney Spears - I Will Still Love You.flac] no longer exists on disk, removing from db
19-2-4 03:35:03.4|Debug|TrackService|Detaching track 36086 from file.
19-2-4 03:35:03.5|Debug|LyricFileService|Deleting Extra from database for track file: [85001] ...Baby One More Time (1999)\08 - Britney Spears - I Will Still Love You.flac
19-2-4 03:35:03.5|Debug|OtherExtraFileService|Deleting Extra from database for track file: [85001] ...Baby One More Time (1999)\08 - Britney Spears - I Will Still Love You.flac
19-2-4 03:35:03.5|Debug|MetadataFileService|Deleting Extra from database for track file: [85001] ...Baby One More Time (1999)\08 - Britney Spears - I Will Still Love You.flac
19-2-4 03:35:03.7|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\09 - Britney Spears - Thinkin' About You.flac] no longer exists on disk, removing from db
19-2-4 03:35:03.8|Debug|TrackService|Detaching track 36087 from file.
19-2-4 03:35:03.8|Debug|LyricFileService|Deleting Extra from database for track file: [85002] ...Baby One More Time (1999)\09 - Britney Spears - Thinkin' About You.flac
19-2-4 03:35:03.8|Debug|OtherExtraFileService|Deleting Extra from database for track file: [85002] ...Baby One More Time (1999)\09 - Britney Spears - Thinkin' About You.flac
19-2-4 03:35:03.8|Debug|MetadataFileService|Deleting Extra from database for track file: [85002] ...Baby One More Time (1999)\09 - Britney Spears - Thinkin' About You.flac
19-2-4 03:35:04.1|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\10 - Britney Spears - E-Mail My Heart.flac] no longer exists on disk, removing from db
19-2-4 03:35:04.1|Debug|TrackService|Detaching track 36078 from file.
19-2-4 03:35:04.1|Debug|LyricFileService|Deleting Extra from database for track file: [85003] ...Baby One More Time (1999)\10 - Britney Spears - E-Mail My Heart.flac
19-2-4 03:35:04.1|Debug|OtherExtraFileService|Deleting Extra from database for track file: [85003] ...Baby One More Time (1999)\10 - Britney Spears - E-Mail My Heart.flac
19-2-4 03:35:04.2|Debug|MetadataFileService|Deleting Extra from database for track file: [85003] ...Baby One More Time (1999)\10 - Britney Spears - E-Mail My Heart.flac
19-2-4 03:35:04.4|Debug|MediaFileTableCleanupService|File [F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)\11 - Britney Spears - The Beat Goes On.flac] no longer exists on disk, removing from db
19-2-4 03:35:04.4|Debug|TrackService|Detaching track 36079 from file.
19-2-4 03:35:04.4|Debug|LyricFileService|Deleting Extra from database for track file: [85004] ...Baby One More Time (1999)\11 - Britney Spears - The Beat Goes On.flac
19-2-4 03:35:04.5|Debug|OtherExtraFileService|Deleting Extra from database for track file: [85004] ...Baby One More Time (1999)\11 - Britney Spears - The Beat Goes On.flac
19-2-4 03:35:04.5|Debug|MetadataFileService|Deleting Extra from database for track file: [85004] ...Baby One More Time (1999)\11 - Britney Spears - The Beat Goes On.flac
19-2-4 03:35:04.7|Debug|ImportDecisionMaker|Analyzing 111/111 files.

**Comment by ta264** [comment] 2019-02-05 07:00
I'd need the actual trace log file, not a copy/paste of the webpage I'm afraid.

https://github.com/lidarr/Lidarr/wiki/Log-Files

Also, what is the full path of the Britney spears album you were testing with?

**Comment by tro-co** [comment] 2019-02-20 02:09
[logs.zip](https://github.com/lidarr/Lidarr/files/2882693/logs.zip)
hope these help...

the full path is: F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)

**Comment by ta264** [comment] 2019-02-20 07:40
I don't think the problem is related to the ellipsis: that folder structure is not supported.  You need to have a folder per artist with albums inside it.

**Comment by tro-co** [comment] 2019-02-22 12:56
Sorry, I forgot the the \ after britney spears.  Should be: F:\Music\Albums\Albums\Britney Spears\...Baby One More Time (1999)

**Comment by ta264** [comment] 2019-02-22 13:11
In that case please can you post a *single* log file that shows that album being removed from Lidar?

It needs to be one of the debug ones.  Lidar.debug.txt will be the most recent, followed by Lidar.debug.0.txt etc

**Comment by tro-co** [comment] 2019-02-22 13:15
Well, it's only doing it during lidarr's scheduled artist\folder scan, but
I believe I can do a manual refresh and it does it then as well. Let me try
that.

**Comment by ta264** [comment] 2019-02-22 13:16
Actually, please can you try on nightly first? The import has been rewritten so it may well work, and any bugs in the old importer won't be fixed.

**Comment by ta264** [comment] 2019-03-11 18:59
Assuming this is OK now but please re-open if you're still having issues on nightly

**Closed by ta264** 2019-03-11 18:59 UTC
Labels: Status: Can't Reproduce, Status: Info Needed
