### ISSUE TITLE
Notifications for albums not tracks

### ISSUE THREAD

**Issue by samuelmaurer** [lidarr/Lidarr#259] opened 2018-03-26 09:26 UTC
## Support / Questions

Background for this request:
I am using Lidarr to manage my favorite artist. When something is grabbed it downloads using rtorrent. After completion a script is executed to convert and import it to my music library using beets. 

It works just fine when i use the script trigger "on rename" and just modify the album folder. But when using "on import" i get an error for every track in the album.

### Description of request and what problem are you looking to solve?
When using custom scripts, or other connection presets, it would be great to have the ability to send a notification when an album is imported. At the moment it sends a notification for every track imported. 

### Other Information
At the moment, when using custom scripts it, it executes for every track and not for just the album.

**Comment by Qstick** [comment] 2018-03-26 11:33
Duplicate of #172

**Closed by Qstick** 2018-03-26 11:33 UTC
