### ISSUE TITLE
Remote Path Mappings

### ISSUE THREAD

**Issue by Dinth** [Lidarr/Lidarr#2116] opened 2021-03-28 17:07 UTC
Lidarr doesnt seem to respect path mappings defined in it's settings. I have a share containing !Complete and !Incomplete folders, which is mounted as /data on Qbittorrent container and as /downloads on Sonarr/Radarr/Lidarr machine. Therefore the completed downloads can be accessed as /data/!Complete in qbittorrent and /downloads/!Complete in Lidarr. 
I have set up the remote path mappings on Sonarr, Radarr and Lidarr as below:
![Screenshot from 2021-03-28 17-58-22](https://user-images.githubusercontent.com/313674/112760545-44d99d00-8fef-11eb-8ead-673446be2c10.png)
And it works perfectly fine on both Sonarr and Radarr, but not on Lidarr - it still tries to copy the completed downloads from /data/!Complete instead of /downloads/!Complete.

![Screenshot from 2021-03-28 18-00-57](https://user-images.githubusercontent.com/313674/112760866-67b88100-8ff0-11eb-815d-c1273f298a5b.png)

I have remoted onto the Lidarr container as user 1001 (same user as Lidarr is running on), and folder /downloads/!Complete is accessible. 

**To Reproduce**

 - Docker: Yes 
 - Mono or .NET Version (System -> Status): 3.1.10 
 - Lidarr Version:  0.8.0.2042-ls7 but have also tried latest from 7.2 

**Trace log***

https://paste.ubuntu.com/p/KgFRXRZ92M/

[AB#186](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/186)

**Comment by bakerboy448** [comment] 2021-03-28 17:08
Please complete the template in full, including trace logs that capture Qbit's response.

more than likely this is not a bug and likely user misconfiguration, remote path map is a dumb find/replace like word

**Comment by Dinth** [comment] 2021-03-28 17:25
> Please complete the template in full, including trace logs that capture Qbit's response.
> 
> more than likely this is not a bug and likely user misconfiguration, remote path map is a dumb find/replace like word

Apologies, i have amended my original post - but the last response from qbittorrent on it is from Lidarr version 0.7.2, i have only recently updated to 0.8 as people on Discord advised me to try 0.8 to fix this issue

**Comment by bakerboy448** [comment] 2021-03-28 17:27
So you haven't reproduced on v0.8 then if you don't have any Qbit response yet...?

also those are info logs which are useless for debugging.

trace, as the template states and as I asked for, are needed

**Comment by Dinth** [comment] 2021-03-28 17:34
OK, i will try to redownload some albums

**Comment by ta264** [comment] 2021-03-28 17:53
Try removing and recreating the path mapping if it's still causing issues. Normally this fixes things.

**Comment by Dinth** [comment] 2021-03-28 18:44
OK, i have added a new album and seems that the import failed at 19:27:
`21-3-28 19:27:58.8|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /data/!Complete/Riverside - 2013 - Shrine Of The New Generation Slaves. Ensure the path exists and the user running Lidarr has the correct permissions to access this file/folder
`
And here's a relevant trace file: https://paste.ubuntu.com/p/yt87xkjnw7/

**Comment by Dinth** [comment] 2021-03-30 07:32
Hi. I have found a workaround, changing path mapping /data/!Complete to /downloads/!Complete to the following: /data to /downloads fixed the issue. Still dont understand why it was not finding /data/!Complete in the paths obviously containing that string earlier.

**Comment by humaintenance** [comment] 2021-09-21 10:01
> You mentioned that remote path mappings are a simple search and replace. If its a regexp, is it possible that an exclamation mark breaks it?

I have this issue also and my path has nothing by text characters. My Remote Path Mappings are set to the exact same as Radarr and Sonarr, which both work perfectly. For some reason Lidarr is unable to decipher the same mapping.

Remote Path: /home/user/Downloads/Completed/
Local Path: /Downloads/Completed/

**Comment by bakerboy448** [comment] 2022-07-13 19:31
Every instance of this not working has been fixed by removing and readding the remote path map.

why it stops working is troublesome to narrow down to say the least

**Comment by frostybrew** [comment] 2022-07-18 06:53
> Every instance of this not working has been fixed by removing and readding the remote path map.

I've tried this to no avail. The paths are nearly identical for sonarr and radarr with zero issues, but lidarr immediately reports it cannot see the folder. The error sometimes self-clears with ZERO input from me, but the import doesn't then take place (similar to when a movie or tv file is moved out and back into the folder.)

What's annoying is the History is saying it was successfully downloaded AND IMPORTED which is why I think Lidarr doesn't attempt to import the file if it eventually clears the error and can successfully see the files. I can provide any files you need, just let me know. Lidarr has been working flawlessly up until now, so it's frustrating to say the least.

**Comment by jptaranto** [comment] 2023-04-20 23:25
This is definitely something worth looking into!

Setup:
Latest version running on Docker
Remote Deluge client
Remote path mappings setup
Rsync script syncs remote client to a temp local directory
Once all files are downloaded they are moved into the path mapped dir
So... files aren't available in the path mapped dir until this sync/move takes place
Same setup works well in Sonarr and Radarr

Problem:
As soon as a file completes downloading in the client - Lidarr marks it as `Download complete and successfully imported`, whilst at the same time leaving this log message: `Import failed, path does not exist or is not accessible by Lidarr`.

The log message is correct - the path doesn't exist - yet! However the status isn't, the files never were imported. Once the rsync eventually takes places, Lidarr doesn't do anything as part of its refresh monitored downloads task - it seems to think the import worked. Typically with my setup Sonarr or Radarr will continue looking in the path mapped folder until the files are actually imported.

**Comment by jptaranto** [comment] 2023-04-21 04:02
I just tested this as a workaround: disable completed download handling and then turn it back on once all in pogress downloads are available in the path mapped dir - they will be imported properly.

**Comment by SuppleCowChunks** [comment] 2023-09-07 21:27
> This is definitely something worth looking into!
> 
> Setup: Latest version running on Docker Remote Deluge client Remote path mappings setup Rsync script syncs remote client to a temp local directory Once all files are downloaded they are moved into the path mapped dir So... files aren't available in the path mapped dir until this sync/move takes place Same setup works well in Sonarr and Radarr
> 
> Problem: As soon as a file completes downloading in the client - Lidarr marks it as `Download complete and successfully imported`, whilst at the same time leaving this log message: `Import failed, path does not exist or is not accessible by Lidarr`.
> 
> The log message is correct - the path doesn't exist - yet! However the status isn't, the files never were imported. Once the rsync eventually takes places, Lidarr doesn't do anything as part of its refresh monitored downloads task - it seems to think the import worked. Typically with my setup Sonarr or Radarr will continue looking in the path mapped folder until the files are actually imported.

I am experiencing this same exact issue. Download completes so quickly the files haven't even started to sync locally and the download activity for the album is removed. I have never had this happen in Radarr/Sonarr with identical configurations.

**Comment by bakerboy448** [comment] 2023-09-07 22:21
> Download completes so quickly the files haven't even started to sync locally 

downloads should be synced as they download
https://wiki.servarr.com/lidarr/troubleshooting#remote-path-mapping

**Comment by bakerboy448** [comment] 2023-12-21 22:23
Closing;  import issues with false positive completion are covered under https://github.com/Lidarr/Lidarr/issues/2746

remote path mapping should be a non-issue

**Closed by bakerboy448** 2023-12-21 22:23 UTC
Labels: Type: Bug

**Comment by nabeelmoeen** [comment] 2024-02-04 14:54
> Every instance of this not working has been fixed by removing and readding the remote path map.
> 
> why it stops working is troublesome to narrow down to say the least

thanks, this worked for me
