### ISSUE TITLE
Feature Request: Soulseek Support

### ISSUE THREAD

**Issue by hughesjs** [lidarr/Lidarr#1100] opened 2020-02-29 01:47 UTC
Usenet is notoriously meh when it comes to music, especially for less mainstream genres. Many people also don't want to use torrents.

Soulseek is pretty much the best place to find even rare, high quality music. Why not add it as a data source (would probably be a hybrid indexer and downloader)?

**Comment by Qstick** [comment] 2020-02-29 02:05
Dupe of #444

**Closed by Qstick** 2020-02-29 02:05 UTC
