### ISSUE TITLE
Ignore/Hide unmapped filed

### ISSUE THREAD

**Issue by Dante2202** [Lidarr/Lidarr#3544] opened 2023-04-17 18:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Deleting tracks from the unmapped list deletes tracks from root folder instead of just deleting track from the unmapped list.  Having thousands of unmapped tracks would take years to go through to match, deleting them isn't a practical solution as users still want to keep the unmapped tracks. 

Potentially going through hundreds/thousands of artist folders and manually selecting each album to move into an “unmonitored” folder would break existing continuity with artist/album categorization.  Also, if you attempt to match unmapped tracks they show back up in the unmapped queue if you have duplicate albums. 

Lidarr is constantly analyzing & attempting to match unmapped files causing user hard drives & servers to take a massive performance hit every time "rescan folders" runs.

Users have a valid reason for having multiple versions of the same album.  Example: Remastered Edition, Deluxe Editions, Anniversary Edition, Vinyl, etc…

While it is understandable that only 1 version of an album is matched in Lidarr, the remaining alternate versions go to the unmapped files queue where they are forever being rescanned in an attempt to match causing performance issues. 

### Describe the solution you'd like

An option to also "Hide/Ignore" unmapped files instead of physically deleting them from root folder.  Deleting files does not solve the issue, most users want to keep unmapped files and just ignore/hide them, not delete them.

### Describe alternatives you've considered

Manually editing the database to assign AlbumId value of unmapped files to a value other than "0", this initially works and clears all unmapped tracks but when a "Rescan Folders" task begins the unmapped files come back.

### Anything else?

Just the ability to hide/ignore unmapped files, I cannot delete my unmapped files.

**Comment by bakerboy448** [comment] 2023-05-15 04:58
Duplicate of #2548

**Closed by bakerboy448** 2023-05-15 04:58 UTC
Labels: Type: Feature Request, Status: Needs Triage
