### ISSUE TITLE
[BUG]: Broken Wiki Links - Import Lists

### ISSUE THREAD

**Issue by farhills** [Lidarr/Lidarr#2384] opened 2021-08-31 17:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Settings > Import Lists > Add New List

The ' More Info' links to the wiki are broken.

![image](https://user-images.githubusercontent.com/83388006/131551065-6f3b1a91-1a08-4b68-b1d5-2931fc88fc3a.png)

### Expected Behavior

Links that work.

### Steps To Reproduce

Settings > Import Lists > Add new list

Click 'more info' on any import list template.

### Environment

```markdown
OS: Unraid 6.9 Docker
Lidarr: 0.8.1.2135
Browser: Chrome 92.0.4515.159
```

### What branch are you running?

Develop

### Anything else?

-

[AB#1542](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1542)

**Comment by farhills** [comment] 2021-08-31 17:52
Duplicate

**Comment by bakerboy448** [comment] 2021-08-31 17:53
This is fixed in nightly.
Duplicate of https://github.com/Lidarr/Lidarr/issues/2318

**Closed** 2021-08-31 17:52 UTC
Labels: Type: Bug, Status: Needs Triage
