### ISSUE TITLE
Option to disable automatic monitoring of new releases

### ISSUE THREAD

**Issue by kromsam** [lidarr/Lidarr#2047] opened 2021-03-06 21:01 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Lidarr automatically adds new releases of the artists I maintain my own library, and let Lidarr upgrade the current library now and then. But I want to make my own decision of what new albums I add.

**Describe the solution you'd like**
An option to disable the behavior where new releases of an artist are automatically monitored.

**Comment by bakerboy448** [comment] 2021-03-06 21:03
believe this is a double dupe

Duplicate of https://github.com/lidarr/Lidarr/issues/2031

Duplicate of https://github.com/lidarr/Lidarr/issues/1831

**Closed by bakerboy448** 2021-03-06 21:03 UTC
Labels: Type: Enhancement
