### ISSUE TITLE
OnTheSpot integration

### ISSUE THREAD

**Issue by xiphosm3** [Lidarr/Lidarr#4748] opened 2024-04-12 14:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I haven't had the best of luck finding a lot of artists available on usenet through a variety of different indexers.

### Describe the solution you'd like

I've recently found a tool called OnTheSpot which allows users to download directly from Spotify.

Could we have this integrated into Lidarr somehow??

### Describe alternatives you've considered

None

### Anything else?

https://github.com/casualsnek/onthespot

**Comment by bakerboy448** [comment] 2024-04-12 14:57
Duplicate of https://github.com/Lidarr/Lidarr/issues/806#issuecomment-1399839627

**Closed by bakerboy448** 2024-04-12 14:57 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by xiphosm3** [comment] 2024-04-12 15:17
Wouldn't say thats quite a duplcate as that thread was referencing different solutions. This solution, along with the author, may be willing to work work you all to come up with a great solution. Onthespot lacks alot of the features you have, but they have virtually every song available through spotify.

**Comment by bakerboy448** [comment] 2024-04-12 15:32
> Not planned native, possible with plug-in

applies regardless
