### ISSUE TITLE
Allow use of Musicbrain "sortname" instead of the "original name" when adding a new artist

### ISSUE THREAD

**Issue by typhoe** [Lidarr/Lidarr#3486] opened 2023-04-02 13:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Let's take this example:
https://musicbrainz.org/artist/a7f7df4a-77d8-4f12-8acd-5c60c93f4de8
The artist is Ryūichi Sakamoto (坂本 龍一, Sakamoto Ryūichi)
My problem is that when I search for him, I use the romanji name "Ryuichi Sakamoto"
Lidarr will find the artist from Musicbrain, but add it using the Kanji from it's name in japanse.
This will be used for filling the artist field in tags, creating the folders....
But for me, non native speaking that language, it makes it hard to find the artist in my audio player...

### Describe the solution you'd like

I'd like for Lidarr to allow us to replace/use the "sortname" instead of the "real/original name" that is already grabbed from Musicbrain metadata when we add an artist.
And of course, use it for everything related to tagging, renaming files, creating folders

### Describe alternatives you've considered

Right now, what I have to do each time is manually rename directory and manually modify the tags, and then ask Lidarr to detect the artist from a manual import.... and obviously, never use the "rename" menu from lidarr ever again for that artist

### Anything else?

![lidarr](https://user-images.githubusercontent.com/881171/229355960-56ad2398-db15-4bef-b34a-657fc59c50e0.png)
Here's what lidarr uses when adding that artist and the folder created.
I'd like to use the "sortname" from musicbrain instead

**Comment by jeff47** [comment] 2023-04-05 00:54
Possibly a duplicate of #3481.  Describes the same issue of non-Roman scripts for artist names.

**Comment by bakerboy448** [comment] 2023-05-15 04:43
Duplicate of https://github.com/Lidarr/Lidarr/issues/3481

**Closed by bakerboy448** 2023-05-15 04:43 UTC
Labels: Type: Feature Request, Status: Needs Triage
