### ISSUE TITLE
Add Renaming Option for Various Artists

### ISSUE THREAD

**Issue by jasonpatrickellykrause** [Lidarr/Lidarr#4654] opened 2024-03-03 14:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

As a Lidarr user, I would like the ability to have a third naming option for Various Artist albums that allows me to use artist names.

### Describe the solution you'd like

Lidarr currently has naming options for:
 - Standard Track Format
 - Multi Disc Track Format
 
 We would like to add a third option for:
  - Various Artist Track Format

### Describe alternatives you've considered

The current alternative is to run a second Lidarr instance. 

### Anything else?

Feature request suggested by Sawkee: https://discord.com/channels/264387956343570434/1028840582270955612/1213634992920465408

**Comment by bakerboy448** [comment] 2024-03-03 15:03
Duplicate of https://github.com/Lidarr/Lidarr/issues/3079

**Closed by bakerboy448** 2024-03-03 15:03 UTC
Labels: Type: Feature Request, Status: Needs Triage
