### ISSUE TITLE
Utilize existing library folders and paths 

### ISSUE THREAD

**Issue by ggibby** [Lidarr/Lidarr#3483] opened 2023-04-01 20:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Individual artists are being sorted by first name, not last name.

### Describe the solution you'd like

Lidarr using existing folder structures as built by the user, including [Last Name, First Name] and [Artist, The] for paths and artist names.

### Describe alternatives you've considered

Manually editing every incorrect file path is very time consuming.

### Anything else?

Other music managers can organize the files, Lidarr should be able to use existing structure and paths.

**Comment by bakerboy448** [comment] 2023-05-15 04:49
Duplicate of https://github.com/Lidarr/Lidarr/issues/590

**Closed by bakerboy448** 2023-05-15 04:49 UTC
Labels: Type: Feature Request, Status: Needs Triage
