### ISSUE TITLE
Vinyls everywhere...

### ISSUE THREAD

**Issue by stenkarlsen** [lidarr/Lidarr#740] opened 2019-04-10 06:51 UTC
**Describe the bug**
Im now with Lidarr, so I might just be blind her.. I added a lot of artists, and everything seemed to work great until i noticed that not all albums where matching very well. After a while I noticed that almost every album in my list where marked as vinyl. This, ofcouce, is not what I wanted. Now im trying to change that profile back to CD, but when I do they get marked as wanted again. 

Is it possible to transfer EVERYTHING to cd again, and still keep the files in my database? Is is also possible to lock the profil to only download cds?

**System info**
 - Lidarr Version: 0.5.0.583
 - Operating System CentOS 7
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.18.1.0

**Comment by ta264** [comment] 2019-04-10 06:54
Duplicate of #186.

Matching is much improved in nightly branch.

**Closed by ta264** 2019-04-10 06:54 UTC
