### ISSUE TITLE
Wanted/missing sorting by artist broken

### ISSUE THREAD

**Issue by ansgaross** [Lidarr/Lidarr#4736] opened 2024-04-07 15:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When on the Wanted/Missing page, clicking on the Artist column header results in "Error fetching missing items". Since sorting setting is stored in a cookie and headers are not visible when the error appears, I have to clear cookies to get rid of the error and Wanted/Missing page working again.

To begin with, I used the default SQLite database, but later moved to PostgreSQL. Did not migrate, started fresh. Not sure if I ever sorted the Wanted/Missing page by artist when using SQLite.

### Expected Behavior

Sorting missing items by Artist works.

### Steps To Reproduce

1. Move Lidarr to PostgreSQL.
2. Start fresh, **don't** migrate database from SQLite.
3. At some point, go to Wanted/Missing in menu.
4. Sort by artist by clicking on the Artist column header.

### Environment

```markdown
- OS: Unraid 6.12.9
- Lidarr: Lidarr 2.1.7.4030
- Docker Install: Yes
- Using Reverse Proxy: Yes, Traefik.
- Browser: Any
- Database: Postgresql 15.5
```

### What branch are you running?

Master

### Trace Logs?

https://gist.github.com/ansgaross/631fd31570163e873d7ecea0d5481760

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2024-04-07 18:45
Duplicate of https://github.com/Lidarr/Lidarr/issues/3392

**Closed by bakerboy448** 2024-04-07 18:45 UTC
Labels: Type: Bug, Status: Needs Triage
