### ISSUE TITLE
Cannot import Spotify playlist with special characters in song titles

### ISSUE THREAD

**Issue by reiser4** [lidarr/Lidarr#1785] opened 2020-11-29 08:14 UTC
**Describe the bug**
When importing a playlist from Spotify, it fails when a song with special characters in title is reached.

**To Reproduce**
1. Install Lidarr on Windows 10
2. Add this song to a Spotify playlist: https://open.spotify.com/track/4BxfXnGbnlibcUUPKog7Ne?si=2Kwld_o2QAmWeUkhfe7haw
3. Import the playlist into Lidarr

**Expected behavior**
The playlist should be fully imported

**Screenshots**
After starting import, reached song nr into playlist:
![image](https://user-images.githubusercontent.com/2445517/100536701-9da44f00-3222-11eb-952e-f95335c36cd8.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10 2004
 - Docker: No
 - Mono or.NET Core Version: 528372: .NET Framework 4.8
 - Browser and Version: chrome (but not relevant here)
 - Lidarr Version 0.7.2.1878
 - Lidarr Branch develop

**Trace Logs**
```
20-11-27 11:50:48.2|Trace|HttpClient|Req: [GET] https://api.lidarr.audio/api/v0.4/search?type=album&query=bv3&artist=bloody%20vinyl
20-11-27 11:50:48.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-11-27 11:50:48.4|Trace|HttpClient|Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=album&query=bv3&artist=bloody%20vinyl: 200.OK (137 ms)
20-11-27 11:50:48.4|Trace|ImportListSyncService|Processing list item 4/275
20-11-27 11:50:48.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-11-27 11:50:48.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-11-27 11:50:48.4|Trace|Http|Req: 42 [GET] /api/v1/health
20-11-27 11:50:48.4|Trace|Http|Req: 43 [GET] /api/v1/diskspace
20-11-27 11:50:48.4|Trace|Http|Req: 44 [GET] /api/v1/system/status
20-11-27 11:50:48.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-11-27 11:50:48.4|Trace|Http|Res: 42 [GET] /api/v1/health: 200.OK (38 ms)
20-11-27 11:50:48.5|Trace|Http|Res: 43 [GET] /api/v1/diskspace: 200.OK (41 ms)
20-11-27 11:50:48.4|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
20-11-27 11:50:48.4|Trace|Http|Res: 44 [GET] /api/v1/system/status: 200.OK (39 ms)
20-11-27 11:50:48.5|Debug|Api|[GET] /api/v1/health: 200.OK (38 ms)
20-11-27 11:50:48.5|Debug|Api|[GET] /api/v1/diskspace: 200.OK (41 ms)
20-11-27 11:50:48.5|Trace|HttpClient|Req: [GET] https://api.lidarr.audio/api/v0.4/search?type=album&query=persona&artist=marracash
20-11-27 11:50:48.5|Debug|Api|[GET] /api/v1/system/status: 200.OK (39 ms)
20-11-27 11:50:48.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-11-27 11:50:48.5|Trace|HttpClient|Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=album&query=persona&artist=marracash: 200.OK (54 ms)
20-11-27 11:50:48.6|Trace|ImportListSyncService|Processing list item 5/275
20-11-27 11:50:48.6|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-11-27 11:50:48.6|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-11-27 11:50:48.6|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-11-27 11:50:48.6|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
20-11-27 11:50:48.6|Trace|HttpClient|Req: [GET] https://api.lidarr.audio/api/v0.4/search?type=album&query=best%20of...green%20grass%20%26%20high%20tides&artist=the%20outlaws
20-11-27 11:50:48.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-11-27 11:50:48.8|Trace|HttpClient|Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=album&query=best%20of...green%20grass%20%26%20high%20tides&artist=the%20outlaws: 301.MovedPermanently (168 ms)
20-11-27 11:50:48.8|Trace|CommandQueueManager|Updating command status
20-11-27 11:50:48.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-11-27 11:50:48.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-11-27 11:50:48.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-11-27 11:50:48.8|Trace|EventAggregator|Publishing CommandExecutedEvent
20-11-27 11:50:48.8|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
20-11-27 11:50:48.8|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
20-11-27 11:50:48.8|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-11-27 11:50:48.8|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-11-27 11:50:48.8|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.7.2.1878] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'Best Of...Green Grass & High Tides' failed. Unable to communicate with LidarrAPI.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewAlbum(String title, String artist) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 260
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 98
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncList(ImportListDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 72
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 174
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 95
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

20-11-27 11:50:49.0|Trace|Scheduler|Pending Tasks: 1
20-11-27 11:50:49.0|Trace|CommandQueueManager|Publishing MessagingCleanup
20-11-27 11:50:49.0|Trace|CommandQueueManager|Checking if command is queued or started: MessagingCleanup
20-11-27 11:50:49.0|Trace|CommandQueueManager|Inserting new command: MessagingCleanup
20-11-27 11:50:49.1|Trace|CommandExecutor|MessagingCleanupCommand -> CleanupCommandMessagingService
20-11-27 11:50:49.1|Trace|CommandQueueManager|Marking command as started: MessagingCleanup
20-11-27 11:50:49.1|Trace|CommandQueueManager|Cleaning up old commands
20-11-27 11:50:49.1|Trace|CommandQueueManager|Updating command status
20-11-27 11:50:49.1|Trace|EventAggregator|Publishing CommandExecutedEvent
20-11-27 11:50:49.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
20-11-27 11:50:49.1|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Messaging.Commands.MessagingCleanupCommand
20-11-27 11:50:49.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
20-11-27 11:50:49.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-11-27 11:50:49.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-11-27 11:50:49.1|Trace|CommandExecutor|MessagingCleanupCommand <- CleanupCommandMessagingService [00:00:00.0228560]
20-11-27 11:50:53.3|Trace|Http|Req: 45 [GET] /api/v1/log/file
20-11-27 11:50:53.3|Trace|Http|Res: 45 [GET] /api/v1/log/file: 200.OK (8 ms)
20-11-27 11:50:53.3|Debug|Api|[GET] /api/v1/log/file: 200.OK (8 ms)
20-11-27 11:50:59.8|Trace|Http|Req: 46 [GET] /logfile/Lidarr.trace.txt
20-11-27 11:50:59.8|Trace|Http|Res: 46 [GET] /logfile/Lidarr.trace.txt: 200.OK (10 ms)
```

**Comment by reiser4** [comment] 2020-11-29 08:16
Likely related to #1705

**Comment by reiser4** [comment] 2020-11-29 09:32
I can import this playlist correctly on latest develop (0148418)

**Comment by ta264** [comment] 2020-12-21 11:19
I believe this is just a duplicate of #1705 and is now fixed

**Closed by ta264** 2020-12-21 11:19 UTC
Labels: Type: Bug
