### ISSUE TITLE
Don't automatically monitor old albums that are added to MusicBrainz

### ISSUE THREAD

**Issue by crafty35a** [lidarr/Lidarr#2031] opened 2021-02-26 21:38 UTC
**Is your feature request related to a problem? Please describe.**

It's pretty common that someone mistakenly adds a duplicate release group of an old album to Musicbrainz. When this happens, Lidarr lists it as a separate album. It will then re-download it, even if you already have that album (or download it for the first time even if you did not have that album monitored)

**Describe the solution you'd like**

There are at least two possible solutions that I can think of:

- Rather than Lidarr automatically monitoring every "new" album that it discovers for an artist, only automatically monitor newly discovered albums that have a release date in the future. This could still result in duplicates for unreleased albums, but typically the duplicate release group will be merged on Musicbrainz before the album is released, so Lidarr wouldn't necessarily grab it twice.
- Don't automatically monitor newly added albums that share a name and release date with an existing album (I assume some bands have multiple albums of the same name, but also checking the release date would avoid this potential issue).

**Comment by bakerboy448** [comment] 2021-02-26 21:39
Duplicate of #1831 

>It's a binary choice - if the artist is monitored, all new albums will be monitored. If the artist is not monitored, new albums will not be monitored.

**Closed by bakerboy448** 2021-02-26 21:39 UTC
Labels: Type: Enhancement
