### ISSUE TITLE
Import issues for artists with accent

### ISSUE THREAD

**Issue by XYZeb** [lidarr/Lidarr#927] opened 2019-08-21 16:04 UTC
### System Information/Logs

**Lidarr Version:0.6.2.883**

**Operating System:OSX10.14**

**.net Framework (Windows) or mono (macOS/Linux) Version:5.2.0.224**

**Link to Log Files (debug or trace):n/a**

**Browser (for UI bugs):**

![image](https://user-images.githubusercontent.com/7441484/63447663-4f57ac00-c434-11e9-8a6b-68d740785466.png)

Looks to be happening for all artists with accents such Röyksopp, José González, Maxïmo Park etc.

Folder name is with accents (created by iTunes) and hasnt changed since first import (yesterday, when I found out about lidarr.

### Additional Information

Triggered by: Used Artist -> Import to import existing music library.  Realised some content was missing so added, and re-ran import by clicking folder path that is now listed.

**Comment by ta264** [comment] 2019-08-21 16:14
I'm afraid I don't understand what the issue is. Please can you explain more clearly what is wrong and what you'd expect to happen?

**Comment by XYZeb** [comment] 2019-08-21 17:09
Sure, I imported my music folder and it went fine.
I ran the import again, and it detected all the artists with accents as new items for import (but shown as existing, so unselectable as per screenshot)
All other artists without accents in their name (such as Nirvana, Madonna, Prince, The Presidents of the USA etc) are not detected as new, and so not re-listed on the import screen.
I'd expect previously detected and added artists with accents to also not be shown on this screen.

If i were to guess what is happening, it seems like the artist matching is running accent removal on on side of the name comparison for existing artists but not for the other.

**Comment by Qstick** [comment] 2019-09-02 15:03
Detection here is done by whether or not the folder is attached to an artist. So somewhere in that logic we are doing something which makes Lidarr think the folder is not attached to an artist.

**Comment by ta264** [comment] 2019-09-05 18:19
This is all going to get a signficant rework in #844 which should fix the issue

**Comment by ta264** [comment] 2020-02-17 15:40
Should have been fixed in #844

**Closed by ta264** 2020-02-17 15:40 UTC
Labels: Type: Bug
