### ISSUE TITLE
Lidarr not waiting for media to appear in remote path then cancels import

### ISSUE THREAD

**Issue by 0x0f906** [Lidarr/Lidarr#4874] opened 2024-06-28 01:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When download client (Deluge) tells Lidarr the media has been downloaded Lidarr looks in the remote directory but does not find the media (because it has not been downloaded locally yet) then cancels the import process, never to restart. 

2024-06-28 01:19:58.1|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /rseedsync/The Clash - Cut The Crap (1985 - Pop) [Flac 16-44]. Ensure the path exists and the user running Lidarr has the correct permissions to access this file/folder

### Expected Behavior

Upon not finding the media in the remote directory should try again and again until it appears. Sonnar, Radarr, & Readarr work this way. 

I use a local shell script and rsync to bring media from a seedbox and Lidarr should wait for it. 

### Environment

```markdown
- OS: 
- Lidarr: Version 2.3.3.4204
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Mozilla
- Database: sqlite
```

### What branch are you running?

Master

### Trace Logs?

2024-06-28 01:19:58.1|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /rseedsync/The Clash - Cut The Crap (1985 - Pop) [Flac 16-44]. Ensure the path exists and the user running Lidarr has the correct permissions to access this file/folder

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2024-06-28 01:43
Duplicate of more issues than I care to search for.

>  I have searched the existing open and closed issues

Please don't check the box claiming you searched but not actually

**Comment by bakerboy448** [comment] 2024-06-28 01:44
Duplicate of https://github.com/Lidarr/Lidarr/issues/2746

**Closed by bakerboy448** 2024-06-28 01:43 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by 0x0f906** [comment] 2024-06-28 01:56
> Duplicate of #2746
> 
> Please actually search rather than simply checking the box....why lie and say you did?
> 
> Also Invalid Bug Report - OP failed to provide trace logs and lied about following the wiki. Why lie when you made no attempt to even follow the wiki?

That's a lot of accusations and assumptions... I did search but not every search is perfect when key words are vague, and you said I didn't follow the wiki when in the issue you linked you yourself state it is a "known" issue. 

I get that people posting "bug reports" that aren't perfect annoy you but try to come down off your high horse and be a human for a little bit. Or maybe it's time to step away from the FOSS community since it clearly cases you duress. 

Anyway thanks for the info, I hope maybe my post has the right keywords to help anyone else with this issue.

**Comment by bakerboy448** [comment] 2024-06-28 01:58
>> # Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

>>  I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain trace - that are relevant and show this issue.

you failed to follow this and lied claiming you did.

users that waste time by failing to complete bug reports properly and thinking they did are actually worse than users that open duplicates....

For future issues - please abide by the requirements of the template or expect them to be closed as invalid as noted may occur in the template

**Comment by 0x0f906** [comment] 2024-06-28 02:03
> > > # Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.
> 
> > > I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain trace - that are relevant and show this issue.
> 
> you failed to follow this and lied claiming you did.
> 
> users that waste time by failing to complete bug reports properly and thinking they did are actually worse than users that open duplicates....
> 
> For future issues - please abide by the requirements of the template or expect them to be closed as invalid as noted may occur in the template

My post was still informational enough that you clearly knew the issue I was having... but yes you are right I failed to provide a trace log. Either way I had my question answered, I see there is a commit that will fix this issue and my post might help others in the future. 

Thanks again! Hope you can find some peace amongst all the idiots that "waste" your time LOL.
