### ISSUE TITLE
Unable to Parse File.

### ISSUE THREAD

**Issue by neuman1812** [lidarr/Lidarr#480] opened 2018-09-07 18:46 UTC
Lidarr Debug Log. 

## Bug Report
```
18-9-7 14:37:55.4|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Unable to parse file
18-9-7 14:37:55.4|Debug|Parser|Starting Tag Parse for /media/plex/complete/The Beatles - Greatest Songs (2018)/18 - Yesterday.mp3
18-9-7 14:37:55.4|Debug|Parser|Audio Properties : MPEG Version 1 Audio, Layer 3, Bitrate: 320, Sample Size: 0, SampleRate: 44100, Channels: 1
18-9-7 14:37:55.4|Debug|QualityParser|Trying to parse quality for /media/plex/complete/The Beatles - Greatest Songs (2018)/18 - Yesterday.mp3
18-9-7 14:37:55.4|Debug|Parser|Quality parsed: MP3-320 v1
18-9-7 14:37:55.4|Warn|ParsingService|Unable to parse track info from path /media/plex/complete/The Beatles - Greatest Songs (2018)/18 - Yesterday.mp3
18-9-7 14:37:55.4|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Unable to parse file
18-9-7 14:37:55.5|Debug|Parser|Starting Tag Parse for /media/plex/complete/The Beatles - Greatest Songs (2018)/19 - Lucy In The Sky With Diamonds.mp3
18-9-7 14:37:55.5|Debug|Parser|Audio Properties : MPEG Version 1 Audio, Layer 3, Bitrate: 320, Sample Size: 0, SampleRate: 44100, Channels: 1
18-9-7 14:37:55.5|Debug|QualityParser|Trying to parse quality for /media/plex/complete/The Beatles - Greatest Songs (2018)/19 - Lucy In The Sky With Diamonds.mp3
18-9-7 14:37:55.5|Debug|Parser|Quality parsed: MP3-320 v1
18-9-7 14:37:55.5|Warn|ParsingService|Unable to parse track info from path /media/plex/complete/The Beatles - Greatest Songs (2018)/19 - Lucy In The Sky With Diamonds.mp3
18-9-7 14:37:55.5|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Unable to parse file
18-9-7 14:37:55.5|Debug|Parser|Starting Tag Parse for /media/plex/complete/The Beatles - Greatest Songs (2018)/20 - Come Together.mp3
18-9-7 14:37:55.5|Debug|Parser|Audio Properties : MPEG Version 1 Audio, Layer 3, Bitrate: 320, Sample Size: 0, SampleRate: 44100, Channels: 1
18-9-7 14:37:55.5|Debug|QualityParser|Trying to parse quality for /media/plex/complete/The Beatles - Greatest Songs (2018)/20 - Come Together.mp3
18-9-7 14:37:55.5|Debug|Parser|Quality parsed: MP3-320 v1
18-9-7 14:37:55.5|Warn|ParsingService|Unable to parse track info from path /media/plex/complete/The Beatles - Greatest Songs (2018)/20 - Come Together.mp3
18-9-7 14:37:55.5|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Unable to parse file
18-9-7 14:37:56.6|Debug|Api|[GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft: 200.OK (14 ms)

```

Version
0.3.1.510
Mono Version
5.14.0.177

**Operating System:**   
Debian Stretch /Rasberry Pi

### Description of request and what problem are you looking to solve?

I was able to search for a an able and download,  but Lidarr is unable to parse the files in the album.

**Comment by Qstick** [comment] 2018-09-08 17:47
What do the file tags look like?

**Comment by neuman1812** [comment] 2018-09-08 18:37
Artist , and song name are the only tags populated.

**Comment by Qstick** [comment] 2018-09-08 20:01
It needs album and track number tags currently as well to make a strong match. This is dupe of #50.  Jump on discord if you want to chat more about these particular failures

**Closed by Qstick** 2018-09-08 20:01 UTC
