### ISSUE TITLE
Control and scheduling of tasks such as Artist refresh and rescan folders

### ISSUE THREAD

**Issue by neilbeul** [lidarr/Lidarr#2217] opened 2021-04-26 00:55 UTC
**Is your feature request related to a problem? Please describe.**
it is taking very long to rescan my folders and refresh the Artists in my library.

**Describe the solution you'd like**
I, and I'm sure other folks in my situation would prefer to do a folder scan once a week and possibly Artists once a month as a scheduled task. In addition, what could be considered is a stop folder scan function as once it running it doesn’t seem to be stoppable like other tasks.

**Describe alternatives you've considered**
Rebooting the sever doesn’t do anything to stop the process as the rescanning simply resumes after the reboot, besides the fact that I've actually seen a second duplicate task get added after the reboot. Recreating the container inside Portainer does however seem to terminate the process which isn’t really a solution, and I've also read that some people have gone down the road of editing the schedule inside the Lidarr.db file which doesn’t appeal to me at all. 

**Additional context**
**Task override**
![image](https://user-images.githubusercontent.com/83190703/116015428-77e86e00-a639-11eb-9c64-bb838ef1b9d3.png)

**Task schedule modifier**
![image](https://user-images.githubusercontent.com/83190703/116015698-7b302980-a63a-11eb-9f6a-38056f32a8f6.png)

**Comment by bakerboy448** [comment] 2021-04-26 00:56
Duplicate of #532

**Comment by ta264** [comment] 2021-04-26 05:56
We have no plans for this. After an initial refresh it'll only do an incremental update given what has changed server side.

**Closed by ta264** 2021-04-26 05:56 UTC
Labels: Type: Enhancement
