### ISSUE TITLE
[BUG]: Import list - 'monitor specific album' monitors all albums for an artist, not specific albums

### ISSUE THREAD

**Issue by Davo1624** [Lidarr/Lidarr#2435] opened 2021-10-05 16:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When importing a spotify playlist there is an option to select `monitor specific album` which should monitor artists but only monitor albums explicitly included in the list. However when this option is selected, all albums are monitored not just the albums explicitly included in the list.

### Expected Behavior

When importing a list, the `monitor specific album` option should only monitor albums explicitly included in the list, not all artist albums.

### Steps To Reproduce

Add a spotify list to Lidarr
Select the `monitor specific album` option
Authenticate and save list
Check artist albums added from the list

### Environment

```markdown
- OS: Docker
- Lidarr: 1.0.0.2327
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Brace
```

### What branch are you running?

Nightly

### Anything else?

Sorry no trace logs available

[AB#1712](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1712)

**Comment by askariya** [comment] 2022-02-23 16:05
This is happening for me too.

**Comment by gfay63** [comment] 2022-04-02 12:51
Same issue here. This seems to be a pretty significant bug that should be fixed, and likely isn't that major a code change?

OS: Windows 10
Lidarr Version: 0.8.1.2135

**Comment by ta264** [comment] 2022-04-02 13:15
Sounds like you're volunteering?

**Comment by gfay63** [comment] 2022-04-02 13:19
@ta264 G'morning.

> Sounds like you're volunteering?

LOL. Maybe?! Actually, I'm digging into this more. It seems like maybe it made a second pass and reset to only the specific album after all? Do you know if it make multiple passes? Anyway, will look into this more after my fantasy baseball league draft. ;)

**Comment by ta264** [comment] 2022-04-02 13:22
If you are up for taking a look then jump on the discord channel and I can provide some guidance. It's been fixed in readarr but I haven't found the time to pull it across to lidarr unfortunately

**Comment by askariya** [comment] 2022-04-04 18:32
I found that editing the Monitor type of the list after creating it won't actually affect it.
Adding a new list and setting it to "monitor specific type" before finalizing fixed this for me (for the most part). 

The caveat is that when it's looking for a specific album, sometimes it downloads a Discography, and instead of pulling out the appropriate album, Lidarr automatically add all of the albums and mark all newly added albums as "Monitored", even if they were previously set to "Unmonitored".

**Comment by bakerboy448** [comment] 2022-07-19 15:50
Duplicate of #2867

**Comment by ta264** [comment] 2022-07-19 16:02
Not a duplicate

**Closed** 2022-08-03 13:23 UTC
Labels: Type: Bug, Area: Import Lists

**Comment by mendoncart** [comment] 2023-01-29 22:35
I'm too having the same problem.

Lidarr is monitoring all the albuns, instead only the album of the track preset at the list.

Using last.fm import from user.
Install on docker.

![image](https://user-images.githubusercontent.com/62950083/215359437-a6686803-1122-4ffa-b8d8-9ef6aca73f3b.png)

![image](https://user-images.githubusercontent.com/62950083/215359553-04a80af1-2500-42e9-a3d2-4c059ae10e3d.png)
