### ISSUE TITLE
Option to Pull Releases with empty/unknown status from Musicbrainz

### ISSUE THREAD

**Issue by h9rst** [Lidarr/Lidarr#4384] opened 2023-12-30 19:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a Huge Libary of very unknown/rare Stuff that has alot of empty Release Status on Musicbrainz. Before i Switched to Lidarr i tagged with Picard, which was no problem. But now i want to Import my Rips into Lidarr and 90% i cant find via Search. Is there a way do grab unknown Status stuff if i search for it, or could there be a feature like the Options for Official, Bootleg etc.? I would edit them, but were Talking about  Thousands of Releases, Singles, Ep, Mixtapes etc. so it would take Weeks + the Time it takes the changes would land in Lidarr.

### Describe the solution you'd like

The best way for me would be like an Option Toggle, like the Ones for Official, Bootlegs etc.

### Describe alternatives you've considered

If there is no plan to Implement a feature like this, a way to change the Code of Lidarr to grab them would be ok too (dont know if this is Possible)

### Anything else?

And if none of this is Possible, is there a way/browser addon to fast edit the Release Status? I know there are Browser Addons to Import Stuff from Discogs etc. but a quick and easy way to change the release status would be a dream

**Comment by bakerboy448** [comment] 2023-12-30 19:46
Duplicate of https://github.com/Lidarr/Lidarr/issues/3731

**Closed by bakerboy448** 2023-12-30 19:46 UTC
Labels: Type: Feature Request, Status: Needs Triage
