### ISSUE TITLE
'No files found are eligible for import' on file synchronization delays

### ISSUE THREAD

**Issue by esticle** [lidarr/Lidarr#1027] opened 2019-10-25 14:35 UTC
**Describe the bug**

"No files found are eligible for import" occurs without any retries.

If your download client takes a while to get files from itself (on another box) to your lidarr installation (say via rclone / rsync / similar process) it appears that Lidarr decides that there is no eligible files to import and never retries.

**To Reproduce**
1. Download anything but ensure your Lidarr install does not see the resulting files
2. Go to Activity -> Queue you should see your download now in Amber saying "No files found are eligible for import" occurs without any retries to rectify this
3. To rectify, click the 'manual import' (little human head) icon on the same line
4. Click 'Import' as everything is in order

**Expected behavior**

I would expect a directory or files that does not "yet" exist to temporarily have an error but for this condition to go away after a number of retries over time, rather than to sit forever in the activity queue in amber until a manual import is done.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Ubuntu 18.04
 - mono 5.20.1.34

**Additional context**

This is not a configuration issue with the remote paths mapping locally, etc. as at times, if the files appear 'quick enough' in totality, downloads get impored automatically. The same happens if for example, a download started by Lidarr, I stop Lidarr, and wait for the files to appear in the right directory completely, and then start Lidarr up again.

Strangely this problem does not present itself under the same circumstances in Sonarr and Radarr.

I'll appreciate it if a retry to try and match downloads to files in the configured paths can occur, or if there is a way to trigger such a retry via the API.

**Comment by ta264** [comment] 2019-10-25 14:42
Duplicate of #945.  This behaviour is not currently supported in Lidarr, unlike Sonarr or Radarr.  If the download client say that files are complete, they must be immediately available for Lidarr to consume.

**Closed by ta264** 2019-10-25 14:42 UTC
