### ISSUE TITLE
Synology: 100% CPU with latest Synology mono and lidarr

### ISSUE THREAD

**Issue by mamema** [Lidarr/Lidarr#625] opened 2019-02-15 08:48 UTC
**Describe the bug**
On a 4 core Synology DS718+ mono (community package v5.8.0.108-11) mono has constantly 25% CPU which means hogging 1 CPU completely

**To Reproduce**
in DSM (latewst version 6.2.1-23824 Update 4, launch from DSM web interface the ressource monitor, select services, select lidarr, see mono cpu % 

**Expected behavior**
not constantly 1 CPU for 1 app

**System info (please complete the following information):**
 - Lidarr Version: [0.5.0.583]
 - Operating System [Synology]
 - mono v5.8.0.108-11

[AB#322](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/322)

**Comment by ta264** [comment] 2019-02-15 08:58
Try it with docker? It's fine on Linux and not sure any devs have a Synology to try to reproduce.

**Comment by mamema** [comment] 2019-02-15 09:01
i'm not using docker because of another layer just to "make things simple". It's an additional layer of complexity. But i will install it to reproduce, if this helps....

**Comment by gismo2004** [comment] 2019-02-15 10:15
Does this occur also when starting with an empty dB? For me on my Ds212j I don't have this until I start to import data. Then it takes some time (depending on amount of music) to fetch data and read files...

**Comment by mamema** [comment] 2019-02-17 17:01
Now tested with docker. It's the same. 100% CPU and after running 1 day 3.9 GB RAM. Of course i have a large music library >50.000 songs, but even though the songs are already scanned and nothing has changed, on every boot and/or restart of lidarr, the scanning starts from the beginning. This is a endless loop. Didn't find a parameter to set "scan changes only".

**Comment by ta264** [comment] 2019-02-17 19:18
Ah in that case it's a feature, not a bug :) we haven't implemented scan changes only yet but it is on the list.

If you let it complete once and disable rescan after refresh it might help for now.

**Comment by rootwyrm** [comment] 2019-02-17 21:02
This is a known issue with mono 5.8.x on busybox which is why it's pegging a single thread. Do **not** expect SynoCommunity mono to behave correctly. An issue has been open requesting SynoCommunity update to a supported version of Mono for several months with little progress. 

https://github.com/SynoCommunity/spksrc/issues/3470

There is a 5.14 test package available in that thread which may be worth trying.

**Comment by tehniemer** [comment] 2019-03-08 17:53
I notice the same behavior on a QNAP NAS with Lidarr running in docker. Lidarr constantly uses about 20% of the CPU.

**Comment by tehniemer** [comment] 2019-03-08 18:07
> Ah in that case it's a feature, not a bug :) we haven't implemented scan changes only yet but it is on the list.
> 
> If you let it complete once and disable rescan after refresh it might help for now.

What does rescan do? I couldn't find it mentioned in the Wiki.

**Comment by ta264** [comment] 2019-03-08 18:17
Refresh refers to updating the list of all available tracks from Musicbrainz.  Rescan means examine your files on disk and see if they match up with anything from Musicbrainz.

**Comment by ta264** [comment] 2021-07-15 10:53
Closing this since we're dropping mono support

**Closed by ta264** 2021-07-15 10:53 UTC
