### ISSUE TITLE
Enable removal of musicbrainz, swap from another service such as the download agent (deemix-deezer)

### ISSUE THREAD

**Issue by robbtate** [Lidarr/Lidarr#3985] opened 2023-08-11 10:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Musicbrainz is not accurate enough.

### Describe the solution you'd like

Instead of being reliant on the metadata from musicbrainz. I would like to see direct integration into the music service used such as pulling metadata from deezer if the tracks are downloaded using deemix.

### Describe alternatives you've considered

None

### Anything else?

No

**Comment by bakerboy448** [comment] 2023-08-26 12:41
No plans to switch from musicbrainz

duplicate of several other existing issues

**Closed by bakerboy448** 2023-08-26 12:41 UTC
Labels: Type: Feature Request, Status: Needs Triage
