### ISSUE TITLE
Import failed but marked as imported

### ISSUE THREAD

**Issue by GregTroar** [Lidarr/Lidarr#3246] opened 2022-12-26 16:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

My Lidarr is not installed on my remote server but rather at home.
Lidarr does not immediately sees the folders until they are downloaded from the remote server back to my home server.
So I have this error: 
Remote download client rTorrent reported files in /mnt/Multimedia/Download/PostProcess/Music/Qrtist-Title-CD-FLAC-2022-iND but this directory does not appear to exist. Likely missing remote path mapping.

In the past it was retrying to re-import the files every minute or so but the problem now is that if I check in Wanted/History the album is marked as downloaded and imported while it was not imported.

The problem seems to be:
1- It is incorrectly flagged as imported while it is not
2- I do not know if it would retry re-importing or not

### Expected Behavior

I would expect Lidarr works as it used to some time ago and not flag the album as properly imported if it was not and also to try to import until it is properly imported.

### Steps To Reproduce

Use the path mapping to convert the real download folder to a temp folder and after download of an album copy the album to the temp folder a few minutes after the download is marked as finished.
As Lidarr will not directly find the album it will produce the behavior I mentioned above.

### Environment

```markdown
- OS: Debian 11
- Lidarr: 1.1.2.2867
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database: Sqlite 3.34.1
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?74cf3e3afe8a58da#5p8fmKh5p3gw3iwYwCm1ovAN2mZ2dmCmHr3Msfdfthys

[AB#4552](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4552)

**Comment by phoenixxx-1** [comment] 2023-03-26 16:30
I am also impacted by this issue.

**Comment by bakerboy448** [comment] 2023-05-15 05:22
Duplicate of #2746

**Closed by bakerboy448** 2023-05-15 05:22 UTC
Labels: Type: Bug, Status: Needs Triage
