### ISSUE TITLE
Native Support for .CUE Files and Lossless Formats (.WV, .APE, etc.)

### ISSUE THREAD

**Issue by gabriellxxix** [Lidarr/Lidarr#5303] opened 2024-12-12 03:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many music collections, especially those from audiophile and archival sources, are stored in formats like `.WV` or `.APE`, often accompanied by `.CUE` sheets. These formats require manual splitting and conversion to integrate into a typical music library. Adding native support for `.CUE` files and these less common lossless formats in Lidarr would streamline the process and make managing these collections more accessible and efficient.

### Describe the solution you'd like

1. **File Detection**  
   - Lidarr should detect and recognize `.CUE` sheets and associated files (`.WV`, `.APE`, etc.) during scans or imports.

2. **Track Splitting**  
   - Automatically split single large audio files into individual tracks using the `.CUE` sheet.

3. **Format Conversion**  
   - Optionally convert the tracks into user-selected formats, such as FLAC or MP3, while preserving audio quality.

4. **Metadata Integration**  
   - Extract metadata from the `.CUE` sheet and align it with Lidarr’s metadata sources for seamless organization.

### Describe alternatives you've considered

1. **Manual Splitting and Conversion**  
   - Using external tools like **CUETools**, **FFmpeg**, or **EAC** (Exact Audio Copy) to manually split `.CUE` files and convert the resulting tracks.  
   - This approach is time-consuming and requires technical knowledge, making it less accessible for many users.

2. **Third-Party Music Managers**  
   - Exploring alternative music management software that offers native support for `.CUE` files and lossless formats.  
   - However, switching platforms sacrifices the seamless integration and unique features Lidarr provides, such as automation and metadata organization.

3. **Custom Scripts**  
   - Writing custom scripts to automate the splitting, conversion, and metadata handling process.  
   - While effective for tech-savvy users, this solution is complex, prone to errors, and lacks integration with Lidarr’s existing features.

4. **Outsourcing Pre-Split Files**  
   - Downloading pre-split versions of the albums from online sources.  
   - This is often impractical due to limited availability and potential legal or quality concerns.

These alternatives all involve significant drawbacks compared to implementing native support within Lidarr, highlighting the value of this feature enhancement.

### Anything else?

- **Relevant Tools and Libraries**  
  - [FFmpeg](https://ffmpeg.org/) – A powerful multimedia framework for format conversion and track splitting.  
  - [CUETools](http://cue.tools/wiki/Main_Page) – A utility specifically designed for splitting `.CUE` files and handling lossless formats.  
  - [Exact Audio Copy (EAC)](https://www.exactaudiocopy.de/) – Another tool commonly used for splitting `.CUE` sheets and extracting audio tracks.  

- **Mockup Example**  
  - **File Import Process**: A screenshot or diagram showing how Lidarr could recognize `.CUE` files and display an option to split and convert tracks.  
  - **Conversion Settings**: A mockup of the user interface where users could select target formats (e.g., FLAC, MP3) and configure settings like bitrate or compression level.

- **Similar Software Features**  
  - Example: Tools like **MusicBee** and **JRiver Media Center** already offer partial support for `.CUE` files and could serve as inspiration for implementation.

- **Community Discussions**  
  - Include links to forums or GitHub issues where this feature has been discussed to showcase interest and gather ideas for execution.

Providing these resources will help the developers visualize and prioritize the feature, ensuring a smoother integration process.

**Comment by bakerboy448** [comment] 2024-12-12 03:57
Duplicate of https://github.com/Lidarr/Lidarr/issues/515

**Closed by bakerboy448** 2024-12-12 03:57 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by bakerboy448** [comment] 2024-12-12 03:59
[Added: Monkey Audio and WavPack support ](https://github.com/Lidarr/Lidarr/commit/499af455669e2bf7f40ddc49871cba13b8f0694e)

Other two already exists
