### ISSUE TITLE
"On Delete" trigger for custom scripts.

### ISSUE THREAD

**Issue by sdfg2** [Lidarr/Lidarr#2969] opened 2022-09-11 16:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Lidarr manages my reference collection of lossless tracks.  On Import/Upgrade, I run a script to normalize and transcode the new tracks, and pass them to beets to manage the lossy tracks.

If I delete something from lidarr, I have no programmatic way of telling beets to do the same.

### Describe the solution you'd like

An "On Delete" trigger for custom scripts that can pass information via environment variables.

### Describe alternatives you've considered

At the moment, the only way is to manually remove them in both lidarr and beets.

### Anything else?

I know radarr and sonarr have this, and having searched the issues I can see that there have been some cherry picked commits pulled in already.  However there didn't seem to be an actual feature request to monitor, which is why I'm raising this.

[AB#3726](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3726)

**Comment by bakerboy448** [comment] 2022-09-15 20:05
Duplicate of #1933

**Closed by bakerboy448** 2022-09-15 20:05 UTC
Labels: Type: Feature Request, Status: Needs Triage
