### ISSUE TITLE
Unable to load tracks

### ISSUE THREAD

**Issue by mebrunner24** [Lidarr/Lidarr#526] opened 2018-11-03 23:26 UTC
**Describe the bug**
Cannot retrieve track information from Lidarr anymore. I was able to drill down Artist -> Album -> Track(s) previously. After I believe the latest update (not 100% certain) I am no longer able to do so. 

**To Reproduce**
1. Go to Artist
2. Click on Album or Manual Import
3. See pictures

**Expected behavior**
I expect to be able to manually import tracks as previously done. Also be able to see individual track listing of albums.

**Screenshots**
![image](https://user-images.githubusercontent.com/35735539/47958212-e5e5da00-df94-11e8-96b3-5ddf31666fde.png)
^When choosing album that is "missing" the song
![image](https://user-images.githubusercontent.com/35735539/47958223-09108980-df95-11e8-8648-474221052c35.png)
^Unable to load tracks.
![image](https://user-images.githubusercontent.com/35735539/47958224-204f7700-df95-11e8-8e22-7ee0fb6b2829.png)
^When clicking on the album name under the artist. I cannot get passed the loading screen

**Logs**
https://gist.github.com/mebrunner24/e6ddae578c4ad665d21d46e2d4c20975.

**System info (please complete the following information):**
 - Lidarr Version: 0.4.0.524
 - Operating System: unRAID docker container -> binhex_lidarr (https://forums.unraid.net/topic/62284-support-binhex-lidarr/)

[AB#457](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/457)

**Comment by Qstick** [comment] 2018-11-04 13:49
Can you post up a debug level log? Your log isn't showing any errors that I can see

**Comment by mebrunner24** [comment] 2018-11-05 01:41
@Qstick Here's the latest debug log https://gist.github.com/mebrunner24/f1c6bf8a1c18771ce39749a9bb951e9a

I searched the album Anon. by Hands like Houses this time

**Comment by Qstick** [comment] 2018-11-06 01:43
Are you seeing in JS console errors?

**Comment by mebrunner24** [comment] 2018-11-06 03:09
@Qstick okay so I think I narrowed down the problem. I have an OpenVPN proxy which I'm running my desktop machine through. 
- When the machine is connected to the proxy, I cannot view the individual tracks. 
- When the machine is NOT connected to the proxy, I can view the individual tracks. 

Windows 10 machine -> Internet options -> Connections -> LAN settings -> proxy server. 

I also have the same proxy going through Lidarr. I've tested this with and without it enabled on Lidarr. It does not matter if it is enabled or not. What matters is if the W10 proxy server is enabled then I cannot view the tracks

**Comment by jeffreyswiggins** [comment] 2019-06-07 11:18
Has this been resolved or is there a work around as it has start to impact me on my ubuntu installation?  I can add albums, see albums, but if I try to view the tracks in an abulm nothing ever loads.  The center panel just spins for ever and I have left it for hours with no results.

**Comment by mebrunner24** [comment] 2019-06-08 00:32
No, it was not resolved. I removed the proxy and gave up on this topic.

**Comment by MammothJerk** [comment] 2020-02-09 18:50
I've still got the same issue.

**Comment by MammothJerk** [comment] 2020-02-12 12:57
I found a workaround, i'm running delugevpn through the same unraid box as lidarr, and connecting with my pc through the privoxy proxy. if i exclude my unraid ip in the proxy settings i dont have the issue. 

It appears privoxy is blocking the call for whatever reason. i'm not that savvy so i'm not sure what this means but maybe someone else can figure out where the problem is.

proxy enabled with no exclusion
![](https://i.imgur.com/tbAeMHS.png)

Proxy enabled with exclusion
![](https://i.imgur.com/y4GzhbR.png)

as you can see only the remote address gets changed

**Comment by bakerboy448** [comment] 2022-07-13 18:45
Closing; No recent reports.  issues appear to have been caused by users' proxies.

**Closed by bakerboy448** 2022-07-13 18:45 UTC
