### ISSUE TITLE
History shows repeating "Track file deleted" over multiple days

### ISSUE THREAD

**Issue by instantdreams** [lidarr/Lidarr#1050] opened 2019-12-18 05:30 UTC
**Describe the bug**
A set of tracks by artists Queens of the Stone Age and Ben Folds Five are reported as deleted every time the "Refresh Artist" task is run.

**To Reproduce**
1. Wait a day since the last run
2. View Activity | History
3. Scroll through "Track file deleted" entries
4. Select Artist or Album to confirm tracks exist in library
5. Open Windows Explorer and confirm tracks exist in folder

**Expected behavior**
For this not to report, and not to delete.

**Screenshots**
![image](https://user-images.githubusercontent.com/15875093/71058289-8d33bb00-211c-11ea-9a06-b5fcbb407d87.png)

**Logs**
See screenshot.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System Windows Server 2016 Essentials
 - .net Framework 4.7.2

**Additional context**
Nothing comes to mind

**Comment by figurefive** [comment] 2020-01-31 02:34
I'm having the same issue or at least an issue that is very similar. The only difference is that the track files being deleted in the history are not limited to two artists but seem to just be random large sections of my library. My activity history for the past 4 days is 730 pages and there have been very few other alterations to my library so it's just filled with "Track file deleted" and always different artists and albums. 

Also on version 0.7.1.1381 but am running mine from a docker container on unraid.

**Comment by b25-lusis** [comment] 2020-02-28 17:46
I've got the same issue.
I tried to understand what was different for these artists (folder rights, owner...), and I think I found a pattern: For every artists in this list these is also another artist which name is included in the first.

For example I have:
- Courtney Barnett / Courtney Barnett & Kurt Vile
- Chick Corea / Chick Corea Quartet
- Neko Case / Neko Case & Her Boyfriends
Only the second keep being reported in history.

And I feel like @instantdreams has in his libray:
- Queens / Queens of the Stone Age
- Ben Folds / Ben Folds Five ?

Plus being able to remove items from this history could be interresting since I now got 1000+ record pages ;)

**Comment by BugsyLansky** [comment] 2020-02-28 17:47
I've got the same issue.
I tried to understand what was different for these artists (folder rights, owner...), and I think I found a pattern: For every artists in this list these is also another artist which name is included in the first.

For example I have:
- Courtney Barnett / Courtney Barnett & Kurt Vile
- Chick Corea / Chick Corea Quartet
- Neko Case / Neko Case & Her Boyfriends
Only the second keep being reported in history.

And I feel like @instantdreams has in his libray:
- Queens / Queens of the Stone Age
- Ben Folds / Ben Folds Five ?

Plus being able to remove items from this history could be interresting since I now got 1000+ record pages ;)

**Comment by ta264** [comment] 2020-02-28 17:55
That's super helpful, thank you

**Comment by ta264** [comment] 2020-02-28 18:12
I wonder whether this is fixed in nightly with the scanning rework? Please could you test?

**Comment by BugsyLansky** [comment] 2020-03-02 11:07
I tried using hotio's unstable docker image (I hope this what you called 'nightly'), and I couldn't reproduce. I guess I'll have to wait that this feature is included into linuxserver's latest image !

**Comment by ta264** [comment] 2020-03-02 11:19
Thanks for testing. Glad to hear its working.

If you refer linuxserver you can use their preview tag to get the nightly build also.

**Closed** 2020-03-02 11:20 UTC

**Comment by sohipithurts** [comment] 2021-03-10 22:13
Hi, I'm kind of new to all this - I'm experiencing the same issue. I don't really understand the resolution as it is described. I've upgraded to 0.7.2.1878 which I think is the current release but it didn't help. Any suggestions?

**Comment by bakerboy448** [comment] 2021-03-10 23:05
Support Requests -> [Reddit](https://www.reddit.com/r/lidarr/) or [Discord](http://lidarr.audio/discord)
