### ISSUE TITLE
Force download on non-matched search results

### ISSUE THREAD

**Issue by thetrev** [lidarr/Lidarr#471] opened 2018-09-03 08:14 UTC
When searching for a list of releases, matches will be available to download, but anything less - partial matches, for example -have no button to force the download.

In other words, when manually searching, EVERYTHING has a download button. When clicked, a warning can come up (much in the same way sonarr / radarr deals with forced), then it's connected to the release like any other match.

This is because more often than not, Lidarr cannot parse the search item properly, even though it's perfectly valid. At the moment, I'm having to manually download the result, then manually map it to the release, when in fact it was a perfect match but Lidarr couldn't read the name properly. 

I think even when parsing gets better, nothing can beat human interaction.

**Comment by Qstick** [comment] 2018-09-07 03:40
Dupe of #441

**Closed by Qstick** 2018-09-07 03:40 UTC

**Comment by wuast94** [comment] 2018-09-08 14:07
why this is closed ? i see the same behavour at sonarr and radarr sometimes :/

**Comment by wuast94** [comment] 2018-09-08 14:27
yes but that thread is closed to and linking to this thread :/

**Comment by Qstick** [comment] 2018-09-08 14:28
No it’s not, it simply shows that this one linked to it and this one is closed. Go to the top of the issue to see the status of that issue

**Comment by wuast94** [comment] 2018-09-08 14:29
ok my fault :D didn´t say anything :D sry
