### ISSUE TITLE
DNS Resolution Errors

### ISSUE THREAD

**Issue by Spunky17** [lidarr/Lidarr#1947] opened 2021-01-31 17:10 UTC
**To Reproduce**
1. Go to 'System'
2. Click on 'Updates'
3. Check 'Events'
4. See errors noted below

**Expected behavior**
Expected to see the normal updates page with updates noted or that system is up to date.

**Screenshots**
Request Failed. GET /api/v1/update: DNS Name Resolution Failure: 'lidarr.servarr.com'

System.Net.WebException: DNS Name Resolution Failure: 'lidarr.servarr.com'
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x00182] in <ee84f27b3837475094013f9f258418ff>:0 
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x00080] in <ee84f27b3837475094013f9f258418ff>:0 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in <ee84f27b3837475094013f9f258418ff>:0 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in <ee84f27b3837475094013f9f258418ff>:0 
  at NzbDrone.Common.Http.HttpClient.Get[T] (NzbDrone.Common.Http.HttpRequest request) [0x00000] in <ee84f27b3837475094013f9f258418ff>:0 
  at NzbDrone.Core.Update.UpdatePackageProvider.GetRecentUpdates (System.String branch, System.Version currentVersion) [0x000de] in <9556ffeb741f424b870778e08c2c7410>:0 
  at NzbDrone.Core.Update.RecentUpdateProvider.GetRecentUpdatePackages () [0x00018] in <9556ffeb741f424b870778e08c2c7410>:0 
  at Lidarr.Api.V1.Update.UpdateModule.GetRecentUpdates () [0x00000] in <e1780b255a4c4bdb8c92eaab51ae9af2>:0 
  at Lidarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__34_0 (System.Object options) [0x00006] in <f55a582cc6664053853df6efad4bd5de>:0 
  at Nancy.NancyModule+<>c__DisplayClass14_0`1[T].<Get>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyModule+<>c__DisplayClass16_0`1[T].<Get>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.Route`1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0 

Getting similar errors connecting to Jackett which is running on the same host.  Lidarr produces errors saying it can't resolve "localhost" (noted below).

Jackett - ISOHunt2 http://localhost:9117/api/v2.0/indexers/isohunt2/results/torznab/api?t=music&cat=3000,100006&extended=1&apikey=(removed)&offset=0&limit=100 DNS Name Resolution Failure: 'localhost'

Sonarr and Radarr running on the same host using the same mono without any issues.-->

**Platform Information (please complete the following information):**
 - OS: [FreeBSD 12.2-RELEASE-p2]
 - Docker: [No]
 - Mono or .NET Version (System -> Status): [Mono 6.8]
 - Browser and Version (Only needed for UI issues): [Firefox 85.0 64bit]
 - Lidarr Version: [0.8.0.2042]
 - Lidarr Branch: [develop]

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[Lidarr.txt](https://github.com/lidarr/Lidarr/files/5900267/Lidarr.txt)

**Comment by bakerboy448** [comment] 2021-01-31 17:11
this seems more than likely to be a host issue?

Regardless please fill out the template you butchered

**Comment by Spunky17** [comment] 2021-01-31 17:13
I'm trying but it keeps getting messed up when pasting in the logs.

I seriously doubt it's a host issue as noted Sonarr and Radarr and all my other sevices are working just fine.

**Comment by bakerboy448** [comment] 2021-01-31 17:16
actually wait a minute, radarr and lidarr should both be on netcore...?

Are you running BSD or something?

**Comment by Spunky17** [comment] 2021-01-31 17:22
Yes, FreeBSD 12.2-RELEASE-p2 running under Mono.

Everytime I try and fix the post and follow the template it keeps screwing up.  :-(

**Comment by Spunky17** [comment] 2021-01-31 17:24
Okay, that's better...

**Comment by Spunky17** [comment] 2021-01-31 17:26
Uploaded the latest "Lidarr.txt" with the errors.

**Comment by Thefrank** [comment] 2021-01-31 19:06
hi!

how was the package installed? 
pkg/ports should install everything needed depends-wise.  Even TrueNAS plugins should do the same. if installed from tarball did you make sure that you also installed some sort of CA certs?
does `ifconfig` list a `lo0` interface that has a `LOOPBACK` flag on it?
was the jail setup with `allow_raw_sockets=1` ?

**Comment by Spunky17** [comment] 2021-01-31 20:06
Was originally installed via pkg under FreeBSD then switched to develop branch to get updates and used the built in updater from there.  Was working fine until ver 0.8.0.xxxx was pushed out to develop then started getting the errors noted.

yes, ifconfig shows a loopback interface and yes allow_raw_sockets is set.

As noted, all other services like Sonarr, Radarr, Jackett, Headphones, LazyLibrarian are working just fine.  Only one broken is Lidarr with the recent develop version.

Tried falling back to ver 0.7.2.1878 but it appears that there are database updates with the 0.8.0.xxxx branch that makes the older version incompatable.

**Comment by Thefrank** [comment] 2021-01-31 22:29
everything in the 0.8.0.xxxx branch is still listed as pre-release and there is no freebsd-x64 binary listed. I am not quite sure why it tried to even do the update (maybe just grabbed generic linux?). the generic Linux appears to still be under Mono  (both `readelf` and `ldd` say its not an ELF) was mono 6.8 required for the update or does it still run under 5.10 [Makefile uses lang/mono which is 5.10]

everything from pkg/ports should not allow for the installation of updates via the built-in updater as the permissions are usually constructed in way that only pkg can do the updates and things like the update folder arent writable by the *arr client itself or the daemon-ized process of it. I will have to check the one for Lidarr itself but normally the update will fail unless you changed the default ownership or permissions to make it work

what is the output of `pkg info` if its more than one screen just redirect the output to file and attach that.
are all of those programs you listed in the same jail at Lidarr? If yes I suggest moving each to its own jail sooner rather than later as the *arr bases are quickly becoming divergent and might require mutually exclusive dependencies at some point. 

otherwise, I suggest you roll back to the original (pkg) release and use the database from there. you might lose a few days of work depending on how often you make snapshots of the data in the jail less if have app data stored in its own dataset outside of the jail and mounted via fstab and aggressively snapshot that

**Comment by Spunky17** [comment] 2021-02-01 13:12
Thanks for the replies Thefrank and bakerboy448.

As I noted I installed via the normal package installer and switched the setting in General -> Branch to "develop" which is what pulled in this version.

The package installed and setup the permission on the folder to be owned by lidarr with a group of wheel which is the root super group.

**Comment by Thefrank** [comment] 2021-02-01 18:59
Still not sure how the update was able to fire:

Environment: 
`iocage create -r 12.2-RELEASE -n lidarrticket defaultrouter=192.168.0.1 dhcp=on vnet=on allow_raw_sockets=1 allow_mlock=1 boot=on`
`iocage exec lidarrticket "pkg install lidarr"`
`iocage exec lidarrticket "sysrc lidarr_enable=YES"`
`iocage exec lidarrticket  "service lidarr start"`
![Screenshot 2021-02-01 114841](https://user-images.githubusercontent.com/1910378/106504880-5f264d00-647c-11eb-9645-0c36b3104451.png)

```
[v0.7.2.1878] NzbDrone.Core.Update.UpdateFolderNotWritableException: Cannot install update because startup folder '/usr/local/share/lidarr' is not writable by the user 'lidarr'.
  at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate (NzbDrone.Core.Update.UpdatePackage updatePackage) [0x0005d] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
  at NzbDrone.Core.Update.InstallUpdateService.Execute (NzbDrone.Core.Update.Commands.ApplicationUpdateCommand message) [0x00091] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
```

**Comment by ta264** [comment] 2021-02-01 19:02
Going to close this as support.  I think this is unlikely to be a lidarr bug, but if you want to dig in further swing by the discord channel

**Closed** 2021-02-01 19:02 UTC
Labels: Type: Support

**Comment by ta264** [comment] 2021-05-04 19:17
As discovered on discord, this was caused by the root folder watcher (which uses Inotify) breaking DNS on BSD

**Comment by DK2Maverick** [comment] 2021-05-06 01:42
> As discovered on discord, this was caused by the root folder watcher (which uses Inotify) breaking DNS on BSD

What was the solution?

**Comment by Thefrank** [comment] 2021-05-06 03:38
turn off root folder monitoring

**Comment by Spunky17** [comment] 2021-05-06 12:42
In the web interface go Settings -> Media Management, scroll down to the File Management section and uncheck the box for "Watch Root Folders for file changes".
