### ISSUE TITLE
File Rejected / Unable to find track / Couldn't parse track errors

### ISSUE THREAD

**Issue by blade316** [lidarr/Lidarr#500] opened 2018-09-19 10:46 UTC
**Describe the bug**
On around 75% of my albums, across multiple artists, I get these same errors when trying to scan through and match in all my music library.

18-9-19 20:03:24.8|Debug|ParsingService|Unable to find track for xxxxxxx
18-9-19 20:03:24.8|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Couldn't parse track from: xxxxxx

The file exists, the album is the correct one, i.e. it has the correct amount of tracks, and the track names are correct etc.

Most of my library is on FLAC format, and it seems to be part of the problem, however I'm unsure why it would import some FLAC files and not others, even from the same album.

**To Reproduce**

For all my bug examples I use the artist Andrea Bocelli, as I have a lot of his albums, so it makes for good testing.

1. Grab any artist and album you have available
2. Make sure you have all the files, 
3. Import it into Lidarr
4. Check and see if any tracks were unable to be matched

**Expected behavior**
As long as your existing library as some sort of decent file naming convention, Lidarr should be able to parse filenames a lot better and make more successful matches. 

**Screenshots**
Andrea Bocelli - Cinema is the example album I am using:

Here are my files:
![image](https://user-images.githubusercontent.com/19606551/45748653-c1d07280-bc4c-11e8-9d82-353d49013f40.png)

Here is what Lidarr thinks I have:

![image](https://user-images.githubusercontent.com/19606551/45748700-d9a7f680-bc4c-11e8-8570-eac943989cd2.png)

**Logs**
Here are the lines relevant to the Cinema album:

18-9-19 20:02:00.8|Info|RefreshAlbumService|Updating Info for Cinema
18-9-19 20:02:02.1|Info|RefreshTrackService|Starting track info refresh for: [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema]
18-9-19 20:02:03.8|Info|RefreshTrackService|Finished track refresh for album: [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema].
18-9-19 20:02:03.8|Debug|RefreshAlbumService|Finished album refresh for Cinema
18-9-19 20:03:10.1|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 01 - Maria (From West Side Story).flac
18-9-19 20:03:10.1|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 01 - Maria (From West Side Story).flac
18-9-19 20:03:11.6|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:11.6|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:01 Maria (From "West Side Story"): FLAC v1
18-9-19 20:03:11.6|Debug|ParsingService|Track [b5eae229-d0eb-440b-873f-6498c790b9f7]Maria (From "West Side Story") selected for Andrea Bocelli - Cinema - 1:01 Maria (From "West Side Story"): FLAC v1
18-9-19 20:03:11.6|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 01 - Maria (From West Side Story).flac is in artist folder, skipping unpacking check
18-9-19 20:03:11.6|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 01 - Maria (From West Side Story).flac' Has the same filesize as existing file
18-9-19 20:03:11.7|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 02 - La Chanson de Lara (From Dr. Zhivago).flac
18-9-19 20:03:11.7|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 02 - La Chanson de Lara (From Dr. Zhivago).flac
18-9-19 20:03:13.2|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:13.2|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:02 La Chanson de Lara (From "Dr. Zhivago"): FLAC v1
18-9-19 20:03:13.2|Debug|ParsingService|Track [381f347e-7b00-47d7-86f7-42b73af66d96]La Chanson de Lara (From "Dr. Zhivago") selected for Andrea Bocelli - Cinema - 1:02 La Chanson de Lara (From "Dr. Zhivago"): FLAC v1
18-9-19 20:03:13.2|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 02 - La Chanson de Lara (From Dr. Zhivago).flac is in artist folder, skipping unpacking check
18-9-19 20:03:13.2|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 02 - La Chanson de Lara (From Dr. Zhivago).flac' Has the same filesize as existing file
18-9-19 20:03:13.2|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 03 - Moon River (From Breakfast at Tiffany's).flac
18-9-19 20:03:13.2|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 03 - Moon River (From Breakfast at Tiffany's).flac
18-9-19 20:03:14.8|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:14.8|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:03 Moon River (From "Breakfast at Tiffany's"): FLAC v1
18-9-19 20:03:14.8|Debug|ParsingService|Track [1823f1c7-7109-43ac-87b1-b0460f60bd55]Moon River (From "Breakfast at Tiffany's") selected for Andrea Bocelli - Cinema - 1:03 Moon River (From "Breakfast at Tiffany's"): FLAC v1
18-9-19 20:03:14.8|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 03 - Moon River (From Breakfast at Tiffany's).flac is in artist folder, skipping unpacking check
18-9-19 20:03:14.8|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 03 - Moon River (From Breakfast at Tiffany's).flac' Has the same filesize as existing file
18-9-19 20:03:14.8|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 04 - E più ti penso (From Once Upon a Time in America).flac
18-9-19 20:03:14.8|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 04 - E più ti penso (From Once Upon a Time in America).flac
18-9-19 20:03:16.4|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:16.4|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:04 E più ti penso (From "Once Upon a Time in America"): FLAC v1
18-9-19 20:03:16.4|Debug|ParsingService|Track [48130214-9523-4480-ad79-86e2489453be]E più ti penso (From "Once Upon a Time in America / Malèna") selected for Andrea Bocelli - Cinema - 1:04 E più ti penso (From "Once Upon a Time in America"): FLAC v1
18-9-19 20:03:16.4|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 04 - E più ti penso (From Once Upon a Time in America).flac is in artist folder, skipping unpacking check
18-9-19 20:03:16.4|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 05 - Be My Love (From The Toast of New Orleans).flac
18-9-19 20:03:16.4|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 05 - Be My Love (From The Toast of New Orleans).flac
18-9-19 20:03:17.9|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:17.9|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:05 Be My Love (From "The Toast of New Orleans"): FLAC v1
18-9-19 20:03:17.9|Debug|ParsingService|Track [12edc9dc-d32d-495b-b523-635a3e706419]Be My Love (From "The Toast of New Orleans") selected for Andrea Bocelli - Cinema - 1:05 Be My Love (From "The Toast of New Orleans"): FLAC v1
18-9-19 20:03:17.9|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 05 - Be My Love (From The Toast of New Orleans).flac is in artist folder, skipping unpacking check
18-9-19 20:03:17.9|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 05 - Be My Love (From The Toast of New Orleans).flac' Has the same filesize as existing file
18-9-19 20:03:18.0|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 06 - The Music of the Night (From The Phantom of the Opera).flac
18-9-19 20:03:18.0|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 06 - The Music of the Night (From The Phantom of the Opera).flac
18-9-19 20:03:19.5|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:19.5|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:06 The Music of the Night (From "The Phantom of the Opera"): FLAC v1
18-9-19 20:03:19.5|Debug|ParsingService|Track [e02c9819-097c-46e0-af85-b311866cd0c0]The Music of the Night (From "The Phantom of the Opera") selected for Andrea Bocelli - Cinema - 1:06 The Music of the Night (From "The Phantom of the Opera"): FLAC v1
18-9-19 20:03:19.5|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 06 - The Music of the Night (From The Phantom of the Opera).flac is in artist folder, skipping unpacking check
18-9-19 20:03:19.6|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 06 - The Music of the Night (From The Phantom of the Opera).flac' Has the same filesize as existing file
18-9-19 20:03:19.6|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 07 - Brucia la terra (From The Godfather).flac
18-9-19 20:03:19.6|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 07 - Brucia la terra (From The Godfather).flac
18-9-19 20:03:21.3|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:21.3|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:07 Brucia la terra (From "The Godfather"): FLAC v1
18-9-19 20:03:21.3|Debug|ParsingService|Track [a8ef07f5-e844-4f3f-8048-de267a68fa5a]Brucia la terra (From "The Godfather") selected for Andrea Bocelli - Cinema - 1:07 Brucia la terra (From "The Godfather"): FLAC v1
18-9-19 20:03:21.3|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 07 - Brucia la terra (From The Godfather).flac is in artist folder, skipping unpacking check
18-9-19 20:03:21.3|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 07 - Brucia la terra (From The Godfather).flac' Has the same filesize as existing file
18-9-19 20:03:21.3|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 08 - Por una cabeza (From Scent of a Woman).flac
18-9-19 20:03:21.3|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 08 - Por una cabeza (From Scent of a Woman).flac
18-9-19 20:03:23.0|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:23.0|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:08 Por una cabeza (From "Scent of a Woman"): FLAC v1
18-9-19 20:03:23.0|Debug|ParsingService|Track [2f658af2-08a7-4e91-be47-47ce8cdb2f99]Por una cabeza (From "Scent of a Woman") selected for Andrea Bocelli - Cinema - 1:08 Por una cabeza (From "Scent of a Woman"): FLAC v1
18-9-19 20:03:23.0|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 08 - Por una cabeza (From Scent of a Woman).flac is in artist folder, skipping unpacking check
18-9-19 20:03:23.0|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 08 - Por una cabeza (From Scent of a Woman).flac' Has the same filesize as existing file
18-9-19 20:03:23.0|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 09 - No llores por mi Argentina (From Evita).flac
18-9-19 20:03:23.0|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 09 - No llores por mi Argentina (From Evita).flac
18-9-19 20:03:24.8|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:24.8|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:09 No llores por mi Argentina (From "Evita"): FLAC v1
18-9-19 20:03:24.8|Debug|ParsingService|Unable to find track for Andrea Bocelli - Cinema - 1:09 No llores por mi Argentina (From "Evita"): FLAC v1
18-9-19 20:03:24.8|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Couldn't parse track from: Andrea Bocelli - Cinema - 1:09 No llores por mi Argentina (From "Evita"): FLAC v1
18-9-19 20:03:24.8|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 10 - L'amore è una cosa meravigliosa (From Love Is a Many-Splendored Thing).flac
18-9-19 20:03:24.8|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 10 - L'amore è una cosa meravigliosa (From Love Is a Many-Splendored Thing).flac
18-9-19 20:03:26.6|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:26.6|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:10 L'amore è una cosa meravigliosa (From "Love Is a Many-Splendored Thing"): FLAC v1
18-9-19 20:03:26.6|Debug|ParsingService|Track [4e0fdd62-0127-47fb-8c6f-eba9939663ee]L'amore è una cosa meravigliosa (From "Love Is a Many-Splendored Thing") selected for Andrea Bocelli - Cinema - 1:10 L'amore è una cosa meravigliosa (From "Love Is a Many-Splendored Thing"): FLAC v1
18-9-19 20:03:26.6|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 10 - L'amore è una cosa meravigliosa (From Love Is a Many-Splendored Thing).flac is in artist folder, skipping unpacking check
18-9-19 20:03:26.6|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 10 - L'amore è una cosa meravigliosa (From Love Is a Many-Splendored Thing).flac' Has the same filesize as existing file
18-9-19 20:03:26.6|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 11 - Mi mancherai (From Il postino + The Postman).flac
18-9-19 20:03:26.6|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 11 - Mi mancherai (From Il postino + The Postman).flac
18-9-19 20:03:28.2|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:28.2|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:11 Mi mancherai (From "Il postino / The Postman"): FLAC v1
18-9-19 20:03:28.2|Debug|ParsingService|Track [3494a0c2-de2d-4203-b909-00d0f8cc41da]Mi mancherai (From "Il postino: The Postman") selected for Andrea Bocelli - Cinema - 1:11 Mi mancherai (From "Il postino / The Postman"): FLAC v1
18-9-19 20:03:28.2|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 11 - Mi mancherai (From Il postino + The Postman).flac is in artist folder, skipping unpacking check
18-9-19 20:03:28.2|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 11 - Mi mancherai (From Il postino + The Postman).flac' Has the same filesize as existing file
18-9-19 20:03:28.2|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 12 - Cheek to Cheek (From Top Hat).flac
18-9-19 20:03:28.2|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 12 - Cheek to Cheek (From Top Hat).flac
18-9-19 20:03:29.8|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:29.8|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:12 Cheek to Cheek (From "Top Hat"): FLAC v1
18-9-19 20:03:29.8|Debug|ParsingService|Track [529ffe89-d3f2-40f8-9956-02e01d6a62f6]Cheek to Cheek (From "Top Hat") selected for Andrea Bocelli - Cinema - 1:12 Cheek to Cheek (From "Top Hat"): FLAC v1
18-9-19 20:03:29.8|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 12 - Cheek to Cheek (From Top Hat).flac is in artist folder, skipping unpacking check
18-9-19 20:03:29.8|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 12 - Cheek to Cheek (From Top Hat).flac' Has the same filesize as existing file
18-9-19 20:03:29.8|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 13 - Sorridi amore vai (From Life Is Beautiful).flac
18-9-19 20:03:29.8|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 13 - Sorridi amore vai (From Life Is Beautiful).flac
18-9-19 20:03:31.3|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:31.3|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:13 Sorridi amore vai (From "Life Is Beautiful"): FLAC v1
18-9-19 20:03:31.3|Debug|ParsingService|Track [bae7a908-1351-413c-a006-8c912bd8cde0]Sorridi amore vai (From "Life Is Beautiful") selected for Andrea Bocelli - Cinema - 1:13 Sorridi amore vai (From "Life Is Beautiful"): FLAC v1
18-9-19 20:03:31.3|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 13 - Sorridi amore vai (From Life Is Beautiful).flac is in artist folder, skipping unpacking check
18-9-19 20:03:31.3|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 13 - Sorridi amore vai (From Life Is Beautiful).flac' Has the same filesize as existing file
18-9-19 20:03:31.3|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 14 - Historia de amor (From Love Story).flac
18-9-19 20:03:31.3|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 14 - Historia de amor (From Love Story).flac
18-9-19 20:03:32.9|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:32.9|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:14 Historia de amor (From "Love Story"): FLAC v1
18-9-19 20:03:32.9|Debug|ParsingService|Track [c9bbe5e4-567b-402e-b402-6edcfa9f714d]Historia de amor (From "Love Story") selected for Andrea Bocelli - Cinema - 1:14 Historia de amor (From "Love Story"): FLAC v1
18-9-19 20:03:32.9|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 14 - Historia de amor (From Love Story).flac is in artist folder, skipping unpacking check
18-9-19 20:03:32.9|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 14 - Historia de amor (From Love Story).flac' Has the same filesize as existing file
18-9-19 20:03:32.9|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 15 - Ol' Man River (From Showboat).flac
18-9-19 20:03:32.9|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 15 - Ol' Man River (From Showboat).flac
18-9-19 20:03:34.4|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:34.4|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:15 Ol' Man River (From "Showboat"): FLAC v1
18-9-19 20:03:34.5|Debug|ParsingService|Unable to find track for Andrea Bocelli - Cinema - 1:15 Ol' Man River (From "Showboat"): FLAC v1
18-9-19 20:03:34.5|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Couldn't parse track from: Andrea Bocelli - Cinema - 1:15 Ol' Man River (From "Showboat"): FLAC v1
18-9-19 20:03:34.5|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 16 - Nelle tue mani (Now We Are Free) (From Gladiator).flac
18-9-19 20:03:34.5|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 16 - Nelle tue mani (Now We Are Free) (From Gladiator).flac
18-9-19 20:03:36.0|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:03:36.0|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:16 Nelle tue mani (Now We Are Free) (From "Gladiator"): FLAC v1
18-9-19 20:03:36.0|Debug|ParsingService|Track [889702f2-a037-4c4b-9e25-785cc51f05d2]Nelle tue mani (Now We Are Free) (From "Gladiator") selected for Andrea Bocelli - Cinema - 1:16 Nelle tue mani (Now We Are Free) (From "Gladiator"): FLAC v1
18-9-19 20:03:36.0|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 16 - Nelle tue mani (Now We Are Free) (From Gladiator).flac is in artist folder, skipping unpacking check
18-9-19 20:03:36.0|Debug|SameFileSpecification|'/media/Andrea Bocelli/Cinema (2015)/Andrea Bocelli - Cinema - 16 - Nelle tue mani (Now We Are Free) (From Gladiator).flac' Has the same filesize as existing file

**System info (please complete the following information):**
Version: 0.4.0.526
Mono Version: 5.12.0
DB Migration: 20
AppData directory: /config
Startup directory: /usr/lib/lidarr
Mode: Console
OS: Docker

**Additional context**
I even tried renaming the two files in question, and copying exactly what is in Lidarr, and that still failed to parse. See below:

Heres the renamed files:

![untitled](https://user-images.githubusercontent.com/19606551/45748721-ea586c80-bc4c-11e8-994d-87b0234bdbbc.png)

Heres the logs:

18-9-19 20:36:01.7|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/Nelle tue mani (Now We Are Free) (From "Gladiator").flac
18-9-19 20:36:01.7|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/Nelle tue mani (Now We Are Free) (From "Gladiator").flac
18-9-19 20:36:03.3|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:36:03.3|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:16 Nelle tue mani (Now We Are Free) (From "Gladiator"): FLAC v1
18-9-19 20:36:03.3|Debug|ParsingService|Track [889702f2-a037-4c4b-9e25-785cc51f05d2]Nelle tue mani (Now We Are Free) (From "Gladiator") selected for Andrea Bocelli - Cinema - 1:16 Nelle tue mani (Now We Are Free) (From "Gladiator"): FLAC v1
18-9-19 20:36:03.3|Debug|NotUnpackingSpecification|/media/Andrea Bocelli/Cinema (2015)/Nelle tue mani (Now We Are Free) (From "Gladiator").flac is in artist folder, skipping unpacking check
18-9-19 20:36:03.3|Debug|Parser|Starting Tag Parse for /media/Andrea Bocelli/Cinema (2015)/No llores por mì Argentina (From "Evita").flac
18-9-19 20:36:03.3|Debug|QualityParser|Trying to parse quality for /media/Andrea Bocelli/Cinema (2015)/No llores por mì Argentina (From "Evita").flac
18-9-19 20:36:04.8|Debug|ParsingService|Cleaning Album title of common matching issues. Cleaned album title is 'Cinema'
18-9-19 20:36:04.8|Debug|ParsingService|Album [8d1d5a35-7c2a-43cf-aa17-2782df20ee20][Cinema] selected for Andrea Bocelli - Cinema - 1:09 No llores por mi Argentina (From "Evita"): FLAC v1
18-9-19 20:36:04.8|Debug|ParsingService|Unable to find track for Andrea Bocelli - Cinema - 1:09 No llores por mi Argentina (From "Evita"): FLAC v1
18-9-19 20:36:04.8|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Couldn't parse track from: Andrea Bocelli - Cinema - 1:09 No llores por mi Argentina (From "Evita"): FLAC v1
18-9-19 20:37:21.2|Debug|TrackService|Linking [Cinema (2015)/Nelle tue mani (Now We Are Free) (From "Gladiator").flac] > [[889702f2-a037-4c4b-9e25-785cc51f05d2]Nelle tue mani (Now We Are Free) (From "Gladiator")]
18-9-19 20:37:21.7|Debug|VideoFileInfoReader|Getting media info from /media/Andrea Bocelli/Cinema (2015)/Nelle tue mani (Now We Are Free) (From "Gladiator").flac
18-9-19 20:37:21.8|Debug|UpdateMediaInfoService|Updated MediaInfo for '/media/Andrea Bocelli/Cinema (2015)/Nelle tue mani (Now We Are Free) (From "Gladiator").flac'
18-9-19 20:37:25.6|Debug|XbmcMetadata|Generating album.nfo for: Cinema
18-9-19 20:37:25.6|Debug|XbmcMetadata|Saving album.nfo for Cinema

**Comment by blade316** [comment] 2018-09-19 10:49
not sure if its the same issue as #50

**Comment by Qstick** [comment] 2018-09-22 09:37
Yea this would be a dupe of #50 . Looks like most of this issues are from your music having extra stuff in the metadata tags. Like `(From Dr. Zhivago)`

**Closed** 2018-09-23 20:31 UTC
