### ISSUE TITLE
Track list isn't loading for Isis band

### ISSUE THREAD

**Issue by ljmerza** [lidarr/Lidarr#1106] opened 2020-03-08 16:56 UTC
**Describe the bug**
Track list isn't loading for Isis band

**To Reproduce**
Go to track list for Isis band and it wont load

**Logs**
```
message: "/music/Isis/Panopticon (2004)/01 - So Did We.flac is not a child of /data/Music/Isis"
description: "NzbDrone.Common.Disk.NotParentException: /music/Isis/Panopticon (2004)/01 - So Did We.flac is not a child of /data/Music/Isis↵  at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath (System.String parentPath, System.String childPath) [0x00021] in <96b70a41daeb490db51c9994341a8d2b>:0 ↵  at Lidarr.Api.V1.TrackFiles.TrackFileResourceMapper.ToResource (NzbDrone.Core.MediaFiles.TrackFile model, NzbDrone.Core.Music.Artist artist, NzbDrone.Core.DecisionEngine.Specifications.IUpgradableSpecification upgradableSpecification) [0x00047] in <2883fe04aa0a46f687bad43f547ee0c6>:0 ↵  at Lidarr.Api.V1.TrackFiles.TrackFileModule+<>c__DisplayClass9_0.<GetTrackFiles>b__1 (NzbDrone.Core.MediaFiles.TrackFile f) [0x00000] in <2883fe04aa0a46f687bad43f547ee0c6>:0 ↵  at System.Collections.Generic.List`1[T].ConvertAll[TOutput] (System.Converter`2[TInput,TOutput] converter) [0x0001a] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 ↵  at Lidarr.Api.V1.TrackFiles.TrackFileModule.GetTrackFiles () [0x00ad7] in <2883fe04aa0a46f687bad43f547ee0c6>:0 ↵  at Lidarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00006] in <26a7215ffa4844618987ce6727897136>:0 ↵  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)↵  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0 "
```

```
20-3-8 12:50:50.6|Info|ExistingExtraFileService|Found 0 extra files
20-3-8 12:54:34.0|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/trackFile

[v0.7.1.1381] NzbDrone.Common.Disk.NotParentException: /music/Isis/Panopticon (2004)/01 - So Did We.flac is not a child of /data/Music/Isis
  at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath (System.String parentPath, System.String childPath) [0x00021] in <96b70a41daeb490db51c9994341a8d2b>:0 
  at Lidarr.Api.V1.TrackFiles.TrackFileResourceMapper.ToResource (NzbDrone.Core.MediaFiles.TrackFile model, NzbDrone.Core.Music.Artist artist, NzbDrone.Core.DecisionEngine.Specifications.IUpgradableSpecification upgradableSpecification) [0x00047] in <2883fe04aa0a46f687bad43f547ee0c6>:0 
  at Lidarr.Api.V1.TrackFiles.TrackFileModule+<>c__DisplayClass9_0.<GetTrackFiles>b__1 (NzbDrone.Core.MediaFiles.TrackFile f) [0x00000] in <2883fe04aa0a46f687bad43f547ee0c6>:0 
  at System.Collections.Generic.List`1[T].ConvertAll[TOutput] (System.Converter`2[TInput,TOutput] converter) [0x0001a] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at Lidarr.Api.V1.TrackFiles.TrackFileModule.GetTrackFiles () [0x00ad7] in <2883fe04aa0a46f687bad43f547ee0c6>:0 
  at Lidarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00006] in <26a7215ffa4844618987ce6727897136>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0 

20-3-8 12:54:34.8|Info|RefreshArtistService|Updating Info for Isis
20-3-8 12:54:34.9|Info|RefreshAlbumService|Updating Info for Oceanic
20-3-8 12:54:35.1|Info|RefreshAlbumService|Updating Info for Wavering Radiant
20-3-8 12:54:35.3|Info|RefreshAlbumService|Updating Info for In the Absence of Truth
20-3-8 12:54:35.4|Info|RefreshAlbumService|Updating Info for Celestial
20-3-8 12:54:35.6|Info|RefreshAlbumService|Updating Info for Panopticon
20-3-8 12:54:35.8|Info|DiskScanService|Scanning Isis
20-3-8 12:54:39.4|Info|DiskScanService|Completed scanning disk for Isis
20-3-8 12:54:39.6|Info|ExistingMetadataImporter|Found 1 existing metadata files
20-3-8 12:54:39.7|Info|ExistingLyricImporter|Found 0 existing lyric files
20-3-8 12:54:39.7|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-3-8 12:54:39.7|Info|ExistingExtraFileService|Found 0 extra files
20-3-8 12:54:39.8|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/trackFile

[v0.7.1.1381] NzbDrone.Common.Disk.NotParentException: /music/Isis/Panopticon (2004)/01 - So Did We.flac is not a child of /data/Music/Isis
  at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath (System.String parentPath, System.String childPath) [0x00021] in <96b70a41daeb490db51c9994341a8d2b>:0 
  at Lidarr.Api.V1.TrackFiles.TrackFileResourceMapper.ToResource (NzbDrone.Core.MediaFiles.TrackFile model, NzbDrone.Core.Music.Artist artist, NzbDrone.Core.DecisionEngine.Specifications.IUpgradableSpecification upgradableSpecification) [0x00047] in <2883fe04aa0a46f687bad43f547ee0c6>:0 
  at Lidarr.Api.V1.TrackFiles.TrackFileModule+<>c__DisplayClass9_0.<GetTrackFiles>b__1 (NzbDrone.Core.MediaFiles.TrackFile f) [0x00000] in <2883fe04aa0a46f687bad43f547ee0c6>:0 
  at System.Collections.Generic.List`1[T].ConvertAll[TOutput] (System.Converter`2[TInput,TOutput] converter) [0x0001a] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at Lidarr.Api.V1.TrackFiles.TrackFileModule.GetTrackFiles () [0x00ad7] in <2883fe04aa0a46f687bad43f547ee0c6>:0 
  at Lidarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00006] in <26a7215ffa4844618987ce6727897136>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0 
```

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System docker container in Ubuntu 18

**Comment by ta264** [comment] 2020-03-08 17:00
Dupe of #1088 or #1012, not enough info provided to determine

**Closed by ta264** 2020-03-08 17:00 UTC
